python/test/unit/language/test_core.py

If the either data type if fp, then fmod should be used for the reference computation.

Fix for binop % (mod) unit test failures.

---

python/test/unit/language/test_core.py
scripts/amd/test.sh

This reverse the skip of most bfloat tests. It skips only bfloat test with issue. Brings the passing rate upto 75%.
``` ==== 542 failed, 3013 passed, 426 skipped, 12 warnings in 299.19s (0:04:59) ====```

unskip most bfloat tests

---

lib/driver/llvm.cc

The issue was that the kernel names were colliding with each other in the cache.  Since the kernel names were based on the date and time, the kernels were getting compiled so fast that a subsequent kernel would end up with the same name as the previous one and would therefore overwrite it in the cache.
It seems to run the same test multiple times but the subsequent runs would end up using the wrong kernel because of the collisions.
It is fixed by appending a randomly generated alphanumeric string to keep the kernel names unique.

Fix for test_bitwise subtests for ROCm.

---

include/triton/Target/HSACO/HSACOTranslation.h
lib/Target/HSACO/HSACOTranslation.cpp
python/triton/compiler.py

object file creation to avoid adding multiple passes to the same TargetMachine.
This fix is necessary to fix issues with the test_floordiv subtest in test_core.py.
Without this fix, the following LLVM error occurs when int64 or uint64 datatypes are used:
`LLVM ERROR: Cannot select: intrinsic %llvm.amdgcn.if`

Duplicate the LLVM objects for AMDGCN assembly generation and AMDGCN

---

include/triton/Conversion/TritonGPUToLLVM/GcnAsmFormat.h
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
python/tests/test_core_amd.py

PR adds an intial div implementaiton.
If you run the test_binop with the only division you get the following result, most of them seem to be mismatch issues. 
``` 
=========================== short test summary info ============================
FAILED python/tests/test_core_amd.py::test_bin_op[int16-float32-/] - Assertio...
FAILED python/tests/test_core_amd.py::test_bin_op[int16-float64-/] - Assertio...
FAILED python/tests/test_core_amd.py::test_bin_op[int32-float64-/] - Assertio...
FAILED python/tests/test_core_amd.py::test_bin_op[int64-int16-/] - AssertionE...
FAILED python/tests/test_core_amd.py::test_bin_op[int64-int32-/] - AssertionE...
FAILED python/tests/test_core_amd.py::test_bin_op[int64-float16-/] - Assertio...
FAILED python/tests/test_core_amd.py::test_bin_op[int64-float64-/] - …
```

add inital div op impl

---

include/triton/Conversion/TritonGPUToLLVM/GcnAsmFormat.h
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
python/tests/test_core_amd.py

ops.
This avoids using GCNBuilder which has the following issues:
1. Performance problems with emitting too many barriers
2. Impossibility of supporting int8 and uint8 because the minimum AMDGPU register width is 16 bits.
More unit tests were included in test_core_amd.py.

Implement triton::LoadOp and triton::StoreOp using LLVM load and store

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
unittest/Conversion/TritonGPUToLLVM/CMakeLists.txt
unittest/Conversion/TritonGPUToLLVM/GcnAsmFormatTest.cpp

In this implementation LoadOp and StoreOp are implemented using inline asm
This implementation is temporary because:
* The location and number of s_waincnt is not optimal
* Memory operations are not vectorized 
* Access to memory is non-coalesced
In the future, this solution should be improved and possibly based on the memref or rocdl dialect to allow the compiler to optimize memory accesses without hindrance

[ROCm] Added LoadOp and StoreOp implementation for AMDGPU

---

python/tests/test_elementwise.py
python/tests/test_ext_elemwise.py
python/triton/__init__.py
python/triton/compiler.py

This PR implements support for linking to AMDGCN bitcode files.
Some unit tests will link directly to this to use the contained math functions.
There is however another item that this PR does not cover: namely specifying the AMDGCN math counterparts in:
https://github.com/ROCmSoftwarePlatform/triton/blob/triton-mlir-phase-2/python/triton/language/libdevice.py
Other unit tests use the functionality in this file and this will be updated to include AMDGCN support in a forthcoming PR.

Add support for AMDGCN bitcode (.bc) files.

---

python/triton/compiler.py

This is fix is needed because the previous logic failed when run on gfx90a.

Fix AMDGPU gfx autodetect logic.

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp

This change fixes the following unit tests:
- one of the subtests in test_elementwise.py
- all the test_bin_op division failures in test_core.py/test_core_amd.py

Remove FDIVOpConversion MLIR pipe stage for ROCm.

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp

This PR enable masked load for Triton on ROCM.  We use the llvm Select op which takes the mask value and picks loaded Values or a false Value(either 0 or a val provided by the user).
This also fully enables vector add. 
``` 
python/tests/test_vecadd.py::test_vecadd_scf_no_mask[4-256-1] PASSED     [  5%]
python/tests/test_vecadd.py::test_vecadd_scf_no_mask[4-1024-256] PASSED  [ 10%]
python/tests/test_vecadd.py::test_vecadd_scf_mask[shape0-2-128-1] PASSED [ 15%]
python/tests/test_vecadd.py::test_vecadd_scf_mask[shape1-2-128-32] PASSED [ 21%]
python/tests/test_vecadd.py::test_vecadd_no_scf[4-256-shape0] PASSED     [ 26%]
python/tests/test_vecadd.py::test_vecadd_no_scf[2-256-shape1] PASSED     [ 31%]
python/tests/test_vecadd.py::test_vecadd_no_scf[1-256-shape2] PASSED     [ 36%] …
```

enable masked load / store

---

python/test/unit/language/test_core_amd.py
python/test/unit/language/test_elementwise.py
python/test/unit/language/test_ext_elemwise.py
python/triton/__init__.py
python/triton/compiler.py

This fixes the modulus (%) operator and many other issues (now and in the future).
The CUDA bitcode libraries are linked in here:
https://github.com/ROCmSoftwarePlatform/triton/blob/triton-mlir-IFU/lib/Target/PTX/PTXTranslation.cpp#L34-L70
The net effect is that they are *always* linked in.
So we do the same for AMDGCN (in Python).
This PR along with the cuda2gcn wrapper will enable many of the advanced math functions to work without intervention from the user.

[Triton-MLIR] Always link in AMDGCN bitcode libraries.

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp

The only test_math_op function that does not work was `exp` so this commit fixes that.

[Triton-MLIR] Fix test_math_op from test_core.py for AMDGPU.

---

python/triton/compiler.py

The parsing of the signature args is unnecessary here as that is done later in the function.
The signature argument is specified in the call to triton.compile.  For example:
kernel = triton.compile(empty_kernel,
**signature**="*fp32,i32,i32",
constants={"BLOCK": 256})

[Triton-MLIR] Triton compile fix signature

---

lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp

This PR fixes handling of `other` elements by fixing the incorrect loading of the other elements but to instead to just use the value directly.

Fix handling of other elements in LoadOpConversion for AMDGPU.

---

lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
python/test/unit/language/test_core_amd.py

Added implementation for scalar atomics:
- atomic_add - uint, int and float types
- atomic_min/max - uint and int
atomic_min/max for float is not supported in LLVM 14. We can wait to moving in upstream to latest LLVM or have to implement these atomics with inline asm.
Tensor variants and atomic_cas, as well as rest of scalar atomics will be introduced with next PR(s).

[ROCM] First part of atomicrmw implementation.

---

CMakeLists.txt
python/setup.py

This PR eliminates the need to pollute the environment with TRITON_USE_ROCM by making it a configurable cmake parameter.
The parameter is conditionally set in setup.py if a ROCm platform is detected.

Eliminate the need to create environment variable for ROCm builds.

---

lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
test/Conversion/AMDGPU/load_store.mlir

Before the patch tt.load and tt.store generated incorrect bitcasts like `%f = llvm.bitcast %i : i32 to f16` (source and destination bitcast' types should have same bitwidth).

[ROCM] Fix incorrect llvm.bitcast creation.

---

scripts/amd/build_dbg_llvm.sh

The script gets latest LLVM 14 release, builds it and
installs to the `build_dbg/install` folder. After that
one can use the installation with `LLVM_SYSPATH` env
variable to override default paths used in
`triton/python/setup.py`
Notes:
1. The whole folder will temporary get ~95GB disk space.
After the last clean command it will be schrinked to ~38GB.
2. Default ld linker gets a lot of memory for debug build,
so number of parallel linker jobs reduced to 4 with
`LLVM_PARALLEL_LINK_JOBS` option. It works with ninja
build system only. Additionally `LLVM_PARALLEL_COMPILE_JOBS`
can be used to reduce parallel compilers processes.

[ROCM][scripts] Add script to build debug LLVM installation.

---

CMakeLists.txt
python/setup.py
python/triton/compiler.py

Add changes to build `triton-mlir-pyt20` on cuda and also to eliminate the need for the TRITON_USE_ROCM env var.

Add fixes for cuda

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/Utility.h
python/test/unit/language/test_core_amd.py

Support of conversions between fp8 and fp16/bf16 on AMDGPU.
With this PR, test_f8_xf16_roundtrip would pass. test_f16_to_f8_rounding currently failed due to the issue with masked store and should pass after the issue with masked store is fixed.

Support of conversions between fp8 and fp16/bf16 on AMDGPU

---

CMakeLists.txt
bin/CMakeLists.txt
bin/triton-translate.cpp
test/Target/tritongpu_to_llvmir.mlir

... and use it in tests instead of python module triton.tools.aot.
The tool is more useful to test/debug at least for LLVM IR generation.
If the patch is ok, the next patch is to update the `triton-translate` util functionality to dump HSACO object file and AMDGCN assembler.

[Test] Enable triton-translate build.

---

python/src/triton.cc
python/test/unit/language/test_core.py

Code snippet from a case in torchbench.
```Python
@triton.jit
def kernel(in_ptr0, out_ptr0, xnumel, rnumel, XBLOCK : tl.constexpr, RBLOCK : tl.constexpr):
xnumel = 2
rnumel = 77
xoffset = tl.program_id(0) * XBLOCK
xindex = xoffset + tl.arange(0, XBLOCK)[:, None]
xmask = xindex < xnumel
rbase = tl.arange(0, RBLOCK)[None, :]
_tmp1 = tl.zeros([XBLOCK, RBLOCK], tl.int64) + -9223372036854775808
```

[BACKEND] Support int64 constant (#1050)

---

lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
python/test/unit/language/test_core_amd.py
python/triton/language/semantic.py

- fixed scalar atomic_rmw implementation for fmin/fmax for f32
- fixed tensor atomic_rmw
- added atomic_cas implementation.
TODO:
- fix atomic_rmw for f16
- implement fmin/fmax for f32 with native instructions (asm inline in case of LLVM 14) instead of tweak used as for NV (added comment in python/triton/language/semantic.py).

[ROCM] Implement next part of atomics.

---

include/triton/Conversion/TritonGPUToLLVM/GCNAsmFormat.h
lib/Conversion/TritonGPUToLLVM/GCNAsmFormat.cpp
unittest/Conversion/TritonGPUToLLVM/GcnAsmFormatTest.cpp

Fixed GcnAsmFormatTest.basic and GcnAsmFormatTest.complexInstruction tests
- Added lost "off" operand
- Removed semicolon after instructions
- Removed redundant comma between args and modifiers

[Test] Fix ctest tests

---

python/setup.py

This cherry-pick is required for pypi whl generation.

[BUILD] Add the missing triton/impl to setup.py (#1042)

---

CMakeLists.txt
python/setup.py

Remove the Triton-Pytorch (weak) circular dependency by eliminating the torch import in setup.py.

Remove torch import in setup.py to check for ROCm.

---

python/triton/compiler.py

Since the llir IR is a string when it is first generated, it should also be a string when we fetch it from the cache.
The original read_bytes() implementation is causing a pytorch 2.0/inductor unit test failure:
`python3 -bb test/inductor/test_torchinductor.py -v CudaTests.test_elu_cuda`
When the test is run with the -bb flag, attempts to convert a byte array to a string result in an error.

Fix llir IR restoration from cache to convert to string.

---

python/tutorials/05-layer-norm.py

A recent IFU is causing an error with compiling the layernorm backward pass so change the unit test and benchmark to run the forward pass.

Change layernorm tutorial unit test and benchmark to run forward pass.

---

lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
lib/Dialect/TritonGPU/Transforms/Combine.cpp
python/test/unit/language/test_core_amd.py

The change enables fall-through FMA path for the ROCM. It works for the float32 type and not all the tensors sizes. The change switches off reporting MMA and async ops support to avoid NV asm inline generation.

[ROCM] Enable part of tl.dot operations.

---

bin/triton-translate.cpp
include/triton/Target/HSACO/HSACOTranslation.h
lib/Target/HSACO/HSACOTranslation.cpp
python/src/triton.cc
python/triton/compiler.py

https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3516
now triton can compile LLVMIR based on the full ISA details instead of manual hardcoding.
I have tested it on gfx90a and gfx1030 (without sramecc and xnack features), and warnings are gone.

Fix warning on some amdgpu arch (i.e., navi21)

---

lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
lib/Target/LLVMIR/LLVMIRTranslation.cpp

Add "agent" syncscope specification to prevent large performance loss for gfx90a.
Add LLVM function attributes to enable fp32 atomic adds for archs that support it (e.g. gfx90a).
This change increases layernorm backward pass performance from 7 GB/sec to 245 gb/sec. on MI200.
Note that this change was not possible with the previous LLVM 14.0 because the AtomicRMWOp builder API did not allow the specification of the syncscope in that LLVM version.

Performance enhancements for AMDGPU atomics.

---

.github/workflows/wheels-rocm.yml

Instead of starting tags with simply 'v', this will help disambiguate future tagging of other branches.

tags must start with 'pytorch-triton-rocm-v'

---

CMakeLists.txt

This fixes error while building with old cmake versions.

Add if guard around policy in CMakeLists.txt

---

python/test/unit/language/test_core_amd.py
python/triton/language/semantic.py

By default Triton generates MLIR with f32 result of the tt.dot operation on f16 typed operands. So we have
"tt.dot(f16,f16,f32)->f32" types in .ttgir. But LLVM FMA instruction requires for the same type for all three operands. So first two operands are implicitly casted f16->f32 as "unrealized_conversion_cast struct{f16,f16,...}->struct{f32,f32}". The change fixed incorrect implicit cast generation.
As the next step to improve f16 typed FMA based dot operation "tt.dot(f16,f16,f16)->f16" could be implemented (perhaps as an option).

[ROCM] Enable float16 and int8 types for FMA based `dot` implementation.

---

.github/workflows/amd-offline-tests.yml
test/Conversion/tritongpu_to_llvm.mlir

This PR disables following sub tests, because they are PTX specific:
- basic_async_wait
- convert_dot
- matmul_kernel_dot_operand_layout
- matmul884_kernel_dot_operand_layout
- matmul_tf32dot
modifty tests, because checks are outdated:
- basic_insert_slice_async_v4
- basic_insert_slice_async_v1
- basic_insert_slice_async_v1_multictas

[Test][LIT] Fix Convertion/tritongpu_to_llvm.mlir crash 

---

CMakeLists.txt

The HIP check does not work during pypi whl generation so force a ROCm build.

Remove HIP check in CMakeLists.txt.

---

bin/triton-translate.cpp
include/triton/Target/HSACO/HSACOTranslation.h
lib/Target/HSACO/HSACOTranslation.cpp
python/src/triton.cc
python/triton/compiler.py

Fixed warnings from https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3516
Now triton can compile LLVMIR based on the full AMD ISA details instead of manual hardcoding.
cherry-pick [#117
](https://github.com/ROCmSoftwarePlatform/triton/pull/117)

Fix xnack and srammec warnings based on ISA info

---

python/triton/compiler.py

Added missing `getDeviceProperties()` implementation that allows to request device properites from `hip_utils`. That is used now to check if shared memory has overflow in `compiler.py`.
Also the interface allows to use other divice features to performance value estimation (clocks rates, etc.).
Also slightly improved HIP runtime error reporting.

[ROCM] Implemented getDeviceProperties() for HIP.

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Conversion/TritonGPUToLLVM/TritonGPUToRockPass.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/DecomposeConversions.cpp

Add LDSEncodingAttr and replace `#shared` with `#lds`.
The ir now looks like follows for the test_dot kernel
``` llvm
#lds = #triton_gpu.lds<{kpack = 4, order = [1, 0]}>
#lds1 = #triton_gpu.lds<{kpack = 4, order = [0, 1]}>
%33 = tt.load %12 {cache = 1 : i32, evict = 1 : i32, isVolatile = false} : tensor<128x64xf16, #blocked1>
%34 = tt.load %25 {cache = 1 : i32, evict = 1 : i32, isVolatile = false} : tensor<64x256xf16, #blocked3>
%35 = triton_gpu.convert_layout %33 : (tensor<128x64xf16, #blocked1>) -> tensor<128x64xf16, #lds>
%36 = triton_gpu.convert_layout %34 : (tensor<64x256xf16, #blocked3>) -> tensor<64x256xf16, #lds1>
// rock ops
```

[dotOp] [rocMLIR] Add LDSEncodingAttr

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Conversion/TritonGPUToLLVM/CMakeLists.txt
lib/Conversion/TritonGPUToLLVM/TritonGPUToRockPass.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/Combine.cpp

Add the MfmaEncodingAttr to describe the result of mfma instructions.
Introduce it in BlockedToMFMA() from the tritongpu-combineops pass.
Now the IR looks like the follows:
```llvm
%cst = arith.constant dense<0.000000e+00> : tensor<128x256xf32, #triton_gpu.mfma<{nonKDim = 32, warpsPerCTA = [2, 4], xdlopsPerWarp0 = [2, 2]}>>
%33 = tt.load %12 {cache = 1 : i32, evict = 1 : i32, isVolatile = false} : tensor<128x64xf16, #blocked>
%34 = tt.load %25 {cache = 1 : i32, evict = 1 : i32, isVolatile = false} : tensor<64x256xf16, #blocked2>
%35 = triton_gpu.convert_layout %33 : (tensor<128x64xf16, #blocked>) -> tensor<128x64xf16, #lds>
%36 = triton_gpu.convert_layout %34 : (tensor<64x256xf16, #blocked2>) -> tensor<64x256xf16, #lds1>
%37 = rock.alloc() : memref<24576xf16, …
```

[dotOp] [rocMLIR] Add MfmaEncodingAttr

---

include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td

Only add the op to the triton gpu dialect. Lowering implementation will be in separate PR.

[dotOp] [rocMLIR] add tensor to memref op to triton gpu dialect

---

lib/Target/HSACO/HSACOTranslation.cpp
python/triton/compiler.py
scripts/amd/check_llvm_src.sh
scripts/amd/lld.sh
test/Target/tritongpu_to_hsaco.mlir

This is to address the following issue:
https://github.com/ROCmSoftwarePlatform/triton/issues/149

Replace hard coded ROCM paths with ROCM_PATH env var.

---

lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/Utility.h
python/triton/tools/aot.py
test/Conversion/AMDGPU/load_store.mlir
test/Conversion/tritongpu_to_llvm.mlir
test/Target/mlir_to_amdgcn_float16_vectorized_load_store.mlir
test/Target/mlir_to_amdgcn_int16_vectorized_load_store.mlir

If applicable, load a 32 bit value and crack it into smaller chunks based on the actual specified data type.
For stores, just store the already packed elements.

Fix for LLVM compiler's inability to auto-vectorize float16 loads and stores on AMDGPU.

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/DotOpHelpers.cpp
lib/Conversion/TritonGPUToLLVM/DotOpHelpers.h
lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
lib/Conversion/TritonGPUToLLVM/Utility.cpp
lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
lib/Dialect/TritonGPU/Transforms/Coalesce.cpp
python/test/unit/language/test_core_amd.py
python/triton/compiler.py
test/Conversion/triton_to_tritongpu.mlir
test/TritonGPU/coalesce.mlir

This PR adds support for warpSize = 64 for AMDGPU to Triton:
* Changing warpSize = 32 to warpSize = 64
* Adding wave64 support for ReduceOp
* Fixing layouts in `test_convert2d` to work with wave64
The current solution with ifdef is temporary and should be improved in the future so that wavefront size can be determined with  `rocminfo`

Adding wave64 support to Triton

---

.github/workflows/integration-tests-dot-rocMLIR.yml
python/setup.py
test/CMakeLists.txt
test/dot-rocMLIR/CMakeLists.txt
test/dot-rocMLIR/Conversion/tritongpu_to_rock.mlir
test/dot-rocMLIR/TritonGPU/combine.mlir
test/dot-rocMLIR/TritonGPU/decompose-conversions.mlir
test/dot-rocMLIR/lit.cfg.py
test/dot-rocMLIR/lit.site.cfg.py.in

This PR adds a github workflow for each PR targeting the `dot-rocMLIR` branch. It includes the following three unit tests:
1. `TritonGPU/combine.mlir`: the result and acc of `tt.dot` should be converted to have `#mfma` encoding.
- This pass was changed to `remove-layout-conversions` here: https://github.com/ROCmSoftwarePlatform/triton/commit/0ec277efc5c6f6b2e20d2cd087339f55b2bdb6a1.
3. `TritonGPU/decompose-conversions.mlir`: the conversion from `#blocked` to `#dot_op` should be decomposed to conversion from `#blocked` to `#lds` and conversion from `#lds` to `#dot_op`.
4. `Conversion/tritongpu_to_rock.mlir`: here we introduced `blockwise_gemm_v2`  and `triton_gpu.memref_to_tensor` and related ops from the rock dialect.

[dotOP] [rocMLIR] Add unit tests for pull requests targeting the dot-rocMLIR branch

---

include/triton/Dialect/TritonGPU/IR/Traits.h
include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
lib/Conversion/TritonGPUToLLVM/TritonGPUToRockPass.cpp
lib/Dialect/TritonGPU/IR/Traits.cpp
test/dot-rocMLIR/Conversion/tritongpu_to_rock.mlir

This PR 
- generates `triton_gpu.tensor_to_memref` to prepare LDS buffer for `blockwise_gemm_v2`.
- adds a trait to verify that the operand and result of `triton_gpu.tensor_to_memref` have the same number of elements.
- Fixes the `tritongpu-to-rock.mlir` unit test.

[dotOp] [rocMLIR] Generate `tensor_to_memref` to prepare LDS buffer for `blockwise_gemm_v2`

---

.github/workflows/integration-tests-dot-rocMLIR.yml

This PR adds a linter to check the style of changed .cpp and .h files using clang-format.

[dot-rocMLIR] [test] Add a linter

---

bin/CMakeLists.txt
bin/triton-opt.cpp
include/triton/Conversion/Passes.h
include/triton/Conversion/Passes.td
include/triton/Conversion/RockToGPU/RockToGPU.h
include/triton/Conversion/TritonGPUToLLVM/RockToLLVMPass.h
include/triton/Conversion/TritonGPUToLLVM/TritonGPUToRockPass.h
include/triton/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.h
lib/Conversion/CMakeLists.txt
lib/Conversion/RockToGPU/CMakeLists.txt
lib/Conversion/RockToGPU/RockToGPU.cpp
lib/Conversion/TritonGPUToLLVM/RockToLLVMPass.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToRockPass.cpp
lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
python/src/triton.cc
test/dot-rocMLIR/Conversion/RockToGPU/alloc.mlir
test/dot-rocMLIR/Conversion/RockToGPU/emptykernel.mlir
test/dot-rocMLIR/Conversion/RockToGPU/memref_global.mlir
test/dot-rocMLIR/Conversion/RockToGPU/misc_ops.mlir
test/dot-rocMLIR/Rock/sanity.mlir

This PR adds the RockToGPU conversion pass from the rocMLIR repo.
- Modify the existing conversion passes to use the per-pass autogenerated macros ([reference](https://discourse.llvm.org/t/psa-deprecation-warning-per-pass-autogenerated-macros-and-pass-options/64998)).
- Add {kernel = 0} as an attribute of the `mlir::func::FuncOp`. This is required by the RockToGPU pass to convert the `func.func` into a `gpu.func`
- Add unit test for the RockToGPU pass
This pass will
1. Convert the `func.func` into `gpu.func`
2. Create a `gpu.module` inside the top level `Module` to wrap the `gpu.func`
3. Add a `gpu.container_module` attribute to the top level `Module`
4. Lower `rock.alloc`

[dotOp] [rocMLIR] Add RockToGPU Conversion pass

---

bin/triton-translate.cpp
lib/Target/HSACO/HSACOTranslation.cpp

This PR fixes option behavior in triton-translate utility and adds additional error reporting message for unsupported triple value.

[FRONTEND] Fix triton-translate default options

---

include/triton/Analysis/Utility.h
lib/Analysis/Alias.cpp
lib/Analysis/Allocation.cpp
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/CMakeLists.txt
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/RockToLLVMPass.cpp
lib/Conversion/TritonGPUToLLVM/TensorMemRefOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TensorMemRefOpToLLVM.h
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
lib/Conversion/TritonGPUToLLVM/TypeConverter.cpp
lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
python/triton/language/semantic.py
test/dot-rocMLIR/Conversion/rock_to_llvm.mlir
test/dot-rocMLIR/Conversion/tritongpu_to_rock.mlir
test/dot-rocMLIR/Rock/sanity.mlir
test/dot-rocMLIR/TritonGPU/combine.mlir
test/dot-rocMLIR/TritonGPU/decompose-conversions.mlir

This PR lowers every left op in the TritonGPU dialect into LLVMIR.
- Add support of `LDSEncodingAttr` in AllocationAnalysis
- `convert_layout` from #blocked to #lds
- `convert_layout` from #mfma to #blocked
- Integrate `tensor_to_memref` and `memref_to_tensor` from #161 
- For `tensor_to_memref` lowering
- Add a GPU memory space attribute conversion to the LLVMTypeConverter
- Use opaque pointer for the base ptr of allocation shared memory
- For `memref_to_tensor` lower, fix the logic in the original PR
- Some misc changes
- Revert #127 to allow dot(f16, f16, f32) -> f32
- Ignore vector type in `ArithConstantSplatOpConversion`

[dotOp] [rocMLIR] Lower TritonGPU to LLVMIR in RockToLLVMPass

---

bin/triton-translate.cpp
lib/Conversion/TritonGPUToLLVM/CMakeLists.txt
lib/Conversion/TritonGPUToLLVM/GpuAllocOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/GpuAllocOpToLLVM.h
lib/Conversion/TritonGPUToLLVM/RockToLLVMPass.cpp

This PR extracts the rewrite patterns for `rock.workitem_id` from RockToGPU pass and implement a simple `rock.alloc()` to LLVMIR rewrite pattern only for private memory allocations. The shared memory allocation case is handled by triton.
TODO:
add tests

[dotOp] [rocMLIR] Lower rock.alloc() to LLVMIR

---

bin/triton-opt.cpp
lib/Conversion/TritonGPUToLLVM/GpuAllocOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/RockToLLVMPass.cpp
lib/Conversion/TritonGPUToLLVM/TensorMemRefOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TypeConverter.cpp
lib/Conversion/TritonGPUToLLVM/TypeConverter.h
lib/Target/LLVMIR/LLVMIRTranslation.cpp

- Added in-rock transforms to lower blockwise_gemm_v2
- Complete the GPUToROCDL conversion patterns to include the following patterns:
- AMDGPUToROCDL
- VectorToLLVM
- MemRefToLLVM
- Note that ArithToLLVM is another pass applied after RockToLLVMPass
- Set index-bitwidth=32 for various passes to eliminate the unresolved
`unrealized_conversion_cast` ops
Now the kernel is generated.
The next PR will fix the runtime error occurred when running the generated kernel.

[dotOp] [rocMLIR] Complete the translation pipeline

---

python/tutorials/02-fused-softmax.py
python/tutorials/05-layer-norm.py

This change is necessary to print all the softmax benchmark output rows.
Without this change, the output gets truncated and only prints 60 rows.
The full test result contains almost 100 rows.

Print all softmax tutorial benchmark rows.

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
python/test/unit/language/test_core_amd.py

Added conversion between Fp8e5m2 and fp16/fp32 on AMDGPU.
The support of conversion between Fp8e5m2 and bf16 will be added later after picking up updates from the upstream.

ROCM support of conversion between Fp8e5m2 and fp16/fp32

---

include/triton/Conversion/Passes.td
include/triton/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.h
include/triton/Dialect/TritonGPU/IR/TritonGPUDialect.td
lib/Conversion/TritonGPUToLLVM/TritonGPUToRockPass.cpp
lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/DecomposeConversions.cpp
lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
python/batch_prof.sh
python/prof.sh
python/src/triton.cc
python/test/unit/language/matmul.py
python/triton/compiler.py
python/triton/runtime/jit.py

This PR enables tuning by the following changes
- `kpack` and `mPerWave`, which are additional tuning parameters for lowering within Rock, are promoted as compilation options as `num_warps`. This means
- At user level, `kpack` and `mPerWave` can be set in the same way as `num_warps`. If not set, the default values are 4 for `kpack` and 16 for `mPerWave`.
- The jit is able to grab `kpack` and `mPerWave` and put them in the set of keyword arguments in the same way as it does for `num_warps`
- During the conversion from triton to tritonGPU, `kpack` and `mPerWave` will be added as module attributes.
- Whenever `kpack` and `mPerWave` is needed, they can be obtained from the module attribute set.
- `prof.sh` is a simple script that can be used to tune a single gemm configs. 
- It traverses a …

[dotOp] [rocMLIR] Enable tuning

---

python/setup.py

since this branch will be used to generate triton packages specifically for pytorch.
This should help avoid any issues with two different triton packages getting installed in our ROCm CI due to mismatching package names

Rename package to pytorch-triton-rocm

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
python/test/unit/language/test_dot_chain-dot.py

The missing piece is the `emitOffsetForMfmaLayout()` function used by `emitIndices()` to compute the offset of each element for the current thread. This is required by `convert_layout #mfma -> #lds`, which is present in chained-dot case but not in single-dot case. 
In chain-dot case, the result of the first dot (#mfma) is used as one of the operands (#dot_op) of the second dot. Therefore, a convert_layout is inserted to convert #mfma to #dot_op, which is decomposed to
`convert_layout #mfma -> #lds` and `convert_layout #lds -> #dot_op`.

[dotOp] [rocMLIR] Support chained dot in test_dot (without k-loop)

---

lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
test/Conversion/tritongpu_to_llvm.mlir

Fixed bug when `AtomicRMWOp` fails to process packed f16 operands.

[ROCM] Fixed `tt.atomic_rmw` for f16 type.

---

.github/workflows/amd-offline-tests.yml

This PR fixes version of container that is used for offline tests. This ensures that release of new "latests" container will not affect our ci.

[CI] Fix version of container image for offline tests

---

include/triton/Analysis/Utility.h
include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Analysis/Allocation.cpp
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MFMA.cpp
lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/DecomposeConversions.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
python/test/unit/language/test_core_amd.py
python/test/unit/operators/test_flash_attention.py
python/triton/ops/flash_attention.py
python/tutorials/06-fused-attention.py
test/Conversion/tritongpu_to_llvm.mlir

This PR optimizes flash attention algorithm on AMD MI100/200 GPUs by keeping results of dot operations in registers instead of going trough LDS memory.
Currently, this optimizations will happen only if:
- Dot A and B operands have fp16 type. Parameters related to type are hard coded.
- WarpsPerCTA[1] in MFMA layout is 1.
In addition to eliminating the constraints mentioned above, this optimization should be generalized to function with any arbitrary chain dot operation. This PR addresses the specific case where the result of the first dot operation is used as operand A (opIdx == 0) in the subsequent dot - a scenario found in FA.
Issue:
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/4788

[FA OPTIMIZATION] Keep results of FA dot operations in registers

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
python/triton/compiler/compiler.py

PR#241 caused performance regression for GEMM performance, and PR#245 depends on PR#241, so we have to revert both to avoid the GEMM performance regression. 
After reverting these two PRs, the best performance we can get for GEMM is (Unit: TFLOPS, larger is better.):
```
M      cuBLAS     Triton
0    256.0    2.036070   1.466540
1    384.0    5.573140   3.976341
2    512.0   11.570494   8.224126
3    640.0   23.918249  12.900787
4    768.0   34.110305  19.391473
5    896.0   49.677011  25.328279
6   1024.0   59.918627  31.880696
7   1152.0   50.825260  34.094899
8   1280.0   68.985262  42.555845
9   1408.0   84.278666  42.446917
10  1536.0   58.149528  51.888298
11  1664.0   80.549702  42.535283
12  1792.0   90.938448  49.404061
13  1920.0  102.045671  51.229645
14  2048.0  115.828971 …
```

revert PR#245 and #241 for gemm performance regression

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
python/test/unit/language/test_core_amd.py

This PR is a workaround for the function `tl.num_programs()` to return correct value. Reason for this problem is that mlir::gpu gridDimOp has a bug for gridDim to return the number of threads in a kernel (it should return the number of workgroups in the kernel), please see https://reviews.llvm.org/D156009.
So the workaround is to use grimDimOp/blockDimOp as the return value of `tl.num_programs()`. When llvm fix is available and integrated to triton, we should remove this workaround. A unit test is added to ensure that the workaround will be removed when we do upstream.
For issue:
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/5016
https://github.com/ROCmSoftwarePlatform/triton/issues/259

workaround for num_programs() to get correct value

---

lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp

Fix https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/4790
Surprisingly, it reduces LDS usage for `convert_layout #mfma -> #blocked`  because `getScratchConfigForCvtLayout()` uses srcShapePerCTA and dstShapePerCTA to determine the amount of LDS to allocate.
For example: test_dot[128-128-32-4-float32]
Without this PR:
- srcShapePerCTA: 128 x 32 --> dim 0 always gets more
- dstShapePerCTA: 8 x 128
- smemShape: 128 x 132 (with some padding) --> 67584 bytes
After this PR:
- srcShapePerCTA: 64 x 64 --> **more squared layout**
- dstShapePerCTA: 8 x 128
- smemShape: 64 x 132 (with some padding) --> 33792 bytes
For example: test_dot[128-256-32-4-float32]
Without this PR:
- srcShapePerCTA: 64 x 64 --> **now square does not work**
- dstShapePerCTA: 4 x 256
- smemShape: 64 x 260 …

Favor dim 1 (N) when setting warpsPerCTA for non-FA mfma

---

python/triton/language/semantic.py

To enable MFMA instruction for MI300, we need to add gfx940/gfx941 to arch details.

add gfx940/941 to arch details, so MFMA is enabled in codegen

---

lib/Analysis/Utility.cpp
python/test/unit/language/test_core_amd.py
python/triton/language/semantic.py

This PR adds:
- support of FP16 outputs for MFMA dot operations
- fallback to FMA implementation in case MFMA can not handle input sizes

[Dot] [MFMA] [FMA] Update Dot implementation to support upstream tests

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
python/test/unit/language/test_core_amd.py
test/Conversion/tritongpu_to_llvm.mlir

This PR adds generation of vector loads in normal path of MFMA dot operand loading.
This requires shared layout to have contiguous elements which should be loaded by one lane.

[MFMA] [Dot] Support vector loads in normal path

---

python/triton/common/build.py

Running into `fatal error: hip/hip_runtime.h: No such file or directory` with latest wheel due to incorrect directory for ROCm libs
Previously default path was:
`/opt/_internal/cpython-3.8.17/lib/python3.8/site-packages/triton/common/third_party/rocm`
Now
`/opt/_internal/cpython-3.8.17/lib/python3.8/site-packages/triton/common/../third_party/rocm`

Fix default rocm path

---

python/test/unit/language/test_core_amd.py
python/triton/compiler/compiler.py

This PR:
- enables test_dot_mfma_vector_load for fast path in mfma dot op pipeline
- fixes kernel execution for mfma enabled GPUS
- disables mfma layout conversion tests on architectures which can not run these tests

[Tests] Fix some tests in test_core_amd.py

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td

This pr enables generation of swizzled tensors for mfma dot operands.
Related PR: https://github.com/binarman/triton/pull/4
Swizzling pattern is defined by three values: `perPhase`, `maxPhase`, `vecSize`:
The goal of current strategy to maximize `vecSize` by minimizing `maxPhase` and `perPhase` values, while eliminating bank conflicts for mfma 32x32 instructions.
TODO: This code is optimized for  mfma 32x32 operations family, later we need to consider specific cases for mfma 16x16 operations

[MFMA] Swizzle k-major dot operands

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp

If a conversion cannot be eliminated with a high-benefit pattern (e.g., SimplifyConversion, RematerializeBackward), it will be pushed forward in the hope that this will enable the elimination of these conversions later.
However, pushing a conversion forward can introduce more conversions
(op(cvt(arg_0), arg_1, ..., arg_n) -> cvt(op(arg_0, cvt(arg_1), ..., cvt(arg_n))). 
This is why the RematerializeForward pattern performs an analysis to determine whether these added conversions can be eliminated later. The RematerializeBackward pattern, applied after pushing this conversion forward, will eliminate these newly added conversions by reversing the process achieved with RematerializeForward. This can create an infinite loop between these two optimizations. To avoid this, we keep track of the …

Fix FA v2 hanging issue when BLOCK_N=32

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
python/triton/compiler/compiler.py

The rational behind this settings is discussed here: https://github.com/ROCmSoftwarePlatform/triton/pull/285#discussion_r1287931522
Here is the performance on MI250
d | nheads | bs | seqlen | triton-mlir v1 | triton-mlir v2 | this PR v1 | this PR v2
-- | -- | -- | -- | -- | -- | -- | --
64 | 48 | 4 | 1024 | 49.67 | 49.35 | 54.57 | 52.51
64 | 48 | 4 | 2048 | 53.39 | 53.09 | 57.6 | 56.62
64 | 48 | 4 | 4096 | 55.36 | 55.05 | 59.29 | 59.06
64 | 48 | 4 | 8192 | 56.18 | 56.06 | 60.47 | 60.5
64 | 48 | 4 | 16384 | 57.46 | 56.67 | 61.01 | 61.09
64 | 16 | 1 | 1024 | 28.15 | 27.68 | 32.19 | 31.6
64 | 16 | 1 | 2048 | 35.98 | 37.2 | 36.86 | 35.8
64 | 16 | 1 | 4096 | 46.95 | 48.43 | 48.47 | 47.92
64 | 16 | 32 | 1024 | 50.85 | 50.88 | 56.07 | 53.02
64 | 16 | 32 | 2048 | 53.87 | 53.51 | 58.21 | 56.27
64 …

Pick better values for `vecSize` and `maxPhase` for k-major matrices

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv2.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/Prefetch.cpp

We would like to reuse the `MMAv2kWidth` parameter in dotOperandEncodingAttr to represent the number of elements each thread loads for one mfma instruction, a.k.a `k_base`. 
Upstream PR: https://github.com/openai/triton/pull/2119

[NFC] Rename `MMAv2kWidth` to `kWidth`

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MFMA.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
python/test/unit/language/test_core_amd.py

This PR enables bfloat16 support in MFMA dot on MI200.
Used mfma_f32_32x32x8bf16_1k instruction.

[MFMA] MI200 Enable mfma bfloat16

---

lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp

This PR enables optimization for keeping bf16 values in registers between dot operations.

[MFMA] [FA] Keep bf16 results of FA dot operations in registers 

---

lib/Analysis/Allocation.cpp
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
lib/Conversion/TritonGPUToLLVM/Utility.cpp
python/test/unit/language/test_core.py

0-bytes shared mem buffers don't materialize empty allocation buffers; this could lead to unnecessary barriers.
note: reduceop code has become quite messy and will require some cleanup

[CHERRY-PICKED FROM UPSTREAM][BACKEND] no longer uses shared mem or barriers for single-warp reductions (openai#1915)

---

include/triton/Dialect/Triton/Transforms/Passes.h
lib/Dialect/Triton/Transforms/RewriteTensorPointer.cpp
python/src/triton.cc
python/test/unit/language/test_block_pointer.py
python/triton/compiler/compiler.py
python/tutorials/06-fused-attention.py

This commit enables usage of block pointer semantics by enabling rewrite_tensor_pointer_pass that rewrites block pointer loads/stores to legacy loads/stores.
This PR also
- updates the FA fwd kernel from upstream, except that qk's type is set to float32 since it gives better perfomance
- disables bwd kernel in test_op and benchmark. Will add support for bwd kernel in https://github.com/ROCmSoftwarePlatform/triton/pull/303
- tests fail for seqlen = 8192 and 16384 since the standard torch implementation runs out of memory (https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/5154). 
Now we can use the tutorial to get perf numbers for fwd kernel:
```
fused-attention-batch4-head48-d64-fwd:
N_CTX     Triton
0   1024.0  80.377951
1   2048.0  85.872829
2   4096.0  88.415275
3 …
```

Enable usage of block pointer semantics for AMD gpus

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandFMA.cpp

This PR casts FMA dot operands bf16 -> int16 during ttgir -> llvm conversion pass.
Use i16 instead of bf16, because llvm does not support bf16 yet.

[Dot] [FMA] Fix bf16xbf16 FMA dot

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp

This PR reverts rocm specific fix and replaces it with fix from upstream.
Corresponding upstream fix is https://github.com/openai/triton/pull/2184
Reverted rocm fix: #315

Align FP16 FMA dot fix with upstream

---

include/triton/Dialect/TritonGPU/Transforms/Passes.h
include/triton/Dialect/TritonGPU/Transforms/Passes.td
lib/Dialect/TritonGPU/Transforms/CMakeLists.txt
lib/Dialect/TritonGPU/Transforms/StreamPipeline.cpp
python/src/triton.cc
python/triton/compiler/compiler.py

- Prologue: Hoist the pipelinable load operations and shared memory store
for the ramp up stage
- Pipelined Loop: Assemble the loop body minus last iteration
- Prefetch next tile from global into regs (while computing from previous)
- Non-load loop body - Store next tile into shared mem - Epilogue: Peeled non-load loop body for last iteration

[MLIR] Added tritongpu-stream-pipeline pass

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MFMA.cpp
lib/Conversion/TritonGPUToLLVM/TypeConverter.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
python/test/unit/language/test_core_amd.py
python/triton/compiler/compiler.py
python/triton/language/semantic.py
test/Conversion/tritongpu_to_llvm.mlir

This PR makes use of mfma_f32_32x32x4bf16 instruction, available on MI100.

[MFMA] Support BFloat16 on MI100 

---

python/test/unit/language/test_core_amd.py
python/triton/compiler/compiler.py

This PR replaces gpu_has_mfma use with gpu_matrix_core_version and
adds minimal test to check that stream pipeline works

Fix dangling gpu_has_mfma use

---

lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/Utility.cpp
lib/Conversion/TritonGPUToLLVM/Utility.h
python/test/unit/language/test_core_amd.py

The implementation of shuffle up is copied from hcc function [_shfl_up()](https://github.com/RadeonOpenCompute/hcc/blob/f58b93693befa90dcc95426a4fe9944f978d561e/include/hc.hpp#L2879-L2885).
This PR also copied `test_scan2d` and `test_scan_layouts` from `test_core.py` into `test_core_amd.py`.

Fix scanOp lowering by adding support for shfl_up

---

scripts/amd/gemm/matmul.py

This PR merges the two kernels in `triton/scripts/amd/gemm/matmul.py` so now we can use `SPLIT_K=1` to represent the non split_k kernel. 
Previously doing this led to worse performance for large GEMMs that do not need split_k. And this is because split_k kernels set SPLIT_K as the second dim in the grid, which is used to compute offs_k as
```python
offs_k = pid_z * BLOCK_SIZE_K + tl.arange(0, BLOCK_SIZE_K)
a_ptrs = a_ptr + offs_am[:, None] * stride_am + offs_k[None, :] * stride_ak
```
This adds "noise" in the offset of the k dim, which is the fastest changing dim of input A. As summarized in the [pointer arithmetic investigation](https://confluence.amd.com/display/~lixzhang/Pointer+Arithmetic+Investigation), this prevents the LLVM backend to generate maximal vectorized global_load …

[GEMM] [Tuning] Merge split_k and non split_k kernels in GEMM tuning script

---

python/tutorials/06-fused-attention.py

Reverse change introduced by upstream commit https://github.com/openai/triton/commit/5162871c6cae01a8508a309cf21a8e6b68a4c091.
This commit converts result of first dot from fp32 to fp16, but immediately after, result is converted back
to fp32 for softmax. 
Triton IR generated:
%cst_0 = arith.constant dense<0.000000e+00> : tensor<128x64xf16, #mfma>
%94 = arith.truncf %93 : tensor<128x64xf32, #mfma> to tensor<128x64xf16, #mfma>
%95 = arith.addf %94, %cst_0 : tensor<128x64xf16, #mfma>
%96 = arith.extf %95 : tensor<128x64xf16, #mfma> to tensor<128x64xf32, #mfma>
TODO: Investigate whether we can perform softmax in fp16.

Remove redundant fp32->fp16 conversion in FA

---

scripts/amd/gemm/README.md
scripts/amd/gemm/matmul_kernel.py
scripts/amd/gemm/tune_gemm.py

This is the v2 version of the gemm tuning script, which is based on @scxiao's v1 (https://github.com/ROCmSoftwarePlatform/triton/pull/309) and @alefimov-amd's thread pool https://github.com/ROCmSoftwarePlatform/triton/pull/310
@scxiao @oplavsic @alefimov-amd @sjw36 Please give it a shot and let me know if you run into any issues. You can just grab and plug in the two new files from this PR into your branch. See below for example usages.
- `rocprof` is used to measure the time for kernels in the full tuning space
- Each kernel is executed 10 times and the execution time of the last instance is used
- All kernels are compiled in parallel
- Two modes for correctness checking
- During tuning, check correctness with the best perf_config for the current gemm size
- Without tuning, check …

[GEMM] Tuning script v2

---

CMakeLists.txt

In the previous PR https://github.com/ROCmSoftwarePlatform/triton/pull/354 there was an oversight and I forgot to overwrite the initial setting of ROCM_LIBRARIES.

Overwrite initial ROCM_LIBRARIES setting 

---

python/tutorials/06-fused-attention.py

- split the loop into 2 and only pay the masking overhead in the second loop
- add pre_load_v as a tuning parameter
- It turns out on MI250, causal=False likes to preload v but causal=True does not like it
- do not define N_CTX as constexpr
- perform the second dot before sum
- remove qk_scale out of the inner loop
- Added configs in autotuner to tune `waves-per-eu`, `pre_load_v` and `num_stages`. 
- `waves-per-eu`: on MI250, both causal=False and True picked 3 as `waves-per-eu`
- `pre_load_v`: As mentioned before, causal=False picked True and causal=True picked False
- `num_stages`: both picked 1, a.k.a. with stream-pipelining disabled
- With D=64, block size is fixed to BLOCK_M=128, BLOCK_N=64
- Will enable tuning for block size with D=128 in …

Improve FA fwd kernel with causal=True

---

scripts/amd/gemm/tune_gemm.py

Remove the request for `MFMA_TYPE` and use the same [heuristics](https://github.com/ROCmSoftwarePlatform/triton/blob/20f316b19a891a504df53199df21a1407ad4b304/lib/Dialect/TritonGPU/Transforms/AccelerateAMDMatmul.cpp#L98) as https://github.com/ROCmSoftwarePlatform/triton/pull/352 to determine mfma type based on M/N size.
Need to wait for https://github.com/ROCmSoftwarePlatform/triton/pull/352 to merge first.

[GEMM] [Tuning] Parameterize mfma type

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
python/triton/runtime/autotuner.py
python/tutorials/06-fused-attention.py

This PR reduces LDS usage in the epilogue by breaking the `convert_layout #mfma --> #blocked` to multiple `convert_layout`s, each of which uses less LDS than the original one. The issue with the original convert_layout is that padding is used in LDS to avoid bank conflicts. It's simpler than swizzling but extra LDS space is required.
Note:
- This PR only reduces LDS usage if the convert_layout in the epilogue is using more than 64 KB of LDS. And this is the case for **FA fwd D=128**
- For smaller block size, as in the case of **FA fwd D=64**, the convert_layout in the epilogue does not use more than 64 KB LDS but still uses more LDS compared to the block size, which can harm the occupancy. We'll fix this issue for **D=64** in future PR.

[FA fwd D=128] Reduce LDS usage in epilogue

---

python/test/unit/language/test_core_amd.py

This PR is for the failure of test `test_dot_mfma_vector_load`. Reason is the arch name is always set to `gfx90a`. Need to write a function to get the correct gpu_name, then it can pass on all GPUs.

set correct arch info for unit test

---

python/tutorials/03-matrix-multiplication.py

This PR applies some python level optimizations to the matmul tutorial.
Example output (tflops):
```
matmul-performance:                                                                                                                                                                                                                                                                 
M       N        K     rocBLAS      Triton
0  1024.0  1024.0   1024.0   61.006328   49.709120
1  2048.0  2048.0   2048.0  107.804049  101.486683
2  4096.0  4096.0   4096.0  132.395414  121.051490
3  8192.0  8192.0   8192.0  127.727212  123.632272
4  9728.0  8192.0  65536.0  113.326623   111.187546
```
Notes
- best perf configs for 1k, 2k, 4k, and 8k are added in the autotuning. 
- ~For 9728x8192x65536, will update the …

Tweak matmul tutorial on MI2xx GPU

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
test/TritonGPU/combine.mlir
test/TritonGPU/remove-layout-conversions.mlir

This PR fixes layout propagation algorithm in RemoveLayoutConversions pass. In some cases during rewriteSlice process, reduce operation with multiple outputs rewrites only one output layout, which breaks assumption that both outputs should have same layout.
This change is a minimal part of https://github.com/openai/triton/pull/2331 change and small lit test for regression testing.
Fixes #364

[RemoveLayoutConversions] Fix reduce failed infer type error

---

python/tutorials/06-fused-attention-transV.py

Make V tensor k-major so that we don't need to suffer from the transposition issue when `ds_read`ing from LDS for V.  
This PR adds a new version of fused-attention tutorial so that the original one is not "polluted".
Performance:
T: causal=True
F: causal=False
  | triton-mlir | transV | speedup
-- | -- | -- | --
D64 F | 100 | 105.1 | 1.05
D64 F | 108 | 113 | 1.05
D64 F | 107 | 112.8 | 1.05
D64 F | 108 | 113.7 | 1.05
D64 F | 109 | 114.2 | 1.05
D128 F | 93 | 100 | 1.08
D128 F | 103 | 112.79 | 1.10
D128 F | 109 | 119.18 | 1.09
D128 F | 112 | 122.13 | 1.09
D128 F | 113 | 124.16 | 1.10
D64 T | 58 | 65.4 | 1.13
D64 T | 79 | 87.6 | 1.11
D64 T | 92 | 100.4 | 1.09
D64 T | 98 | 106.1 | 1.08
D64 T | 101 | 109.1 | 1.08
D128 T | 47 | 51.68 | 1.10
D128 T | 55 | 60.07 | 1.09
D128 T | 77 | 84.53 | 1.10 …

[FA] Add FA tutorial with transV

---

python/triton/third_party/hip/hip_backend.py

The lines here can cause the following errors on MI300 node. I made these change (removed these lines) before, but after moving to the third-party folder, these lines are back, so make a change again.
RuntimeError: Triton Error [HIP]:  Code: 400, Messsage: invalid resource handle

remove unnecessary arch names

---

python/perf-kernels/06-fused-attention-fwd-transV.py
scripts/amd/benchmark_flash_attention.py
scripts/amd/run_2gcd.sh

This PR supersedes https://github.com/ROCmSoftwarePlatform/triton/pull/307
The benchmark script uses a standalone FA fwd implementation.

Benchmark FA fwd on 2 GCDs

---

python/test/unit/language/test_core_amd.py

Disable mma layout testing by looking at is_hip instead of wave size.
This fixes tests on Navi GPUs with wave size == 32.

[Test] Disable mma layout for amd hardware

---

test/Conversion/tritongpu_to_llvm.mlir
test/Conversion/tritongpu_to_llvm_hopper.mlir

Upstream commit that introduced bypassing shared memory in the case of the reduce_slice lit test: https://github.com/ROCmSoftwarePlatform/triton/commit/4749072fbd04de78f913821308686771c13f775c

Fix reduce_slice lit test

---

scripts/amd/plot_layout.py
scripts/amd/tikzplot.tex

To use, `sudo apt install texlive-full`.
```bash
python3 plot_layout.py
usage: Draw triton layouts [-h] [-shape SHAPE SHAPE SHAPE] [-plot {blocked,dot,wmma,lds}] [-nonKDim {32}] [-sizePerThread SIZEPERTHREAD SIZEPERTHREAD] [-threadsPerWarp THREADSPERWARP THREADSPERWARP] [-warpsPerCTA WARPSPERCTA WARPSPERCTA] [-order ORDER ORDER] [-kpack {4,8}]
[-lds_layout {swizzle,padding,none}] [-lds_access {read,write,none}] [-wave_size {32,64}] [-o O] [-mfmaTrans] [--keep]
optional arguments:
-h, --help            show this help message and exit
-shape SHAPE SHAPE SHAPE
Tensor shape in the form of M,N,K
-plot {blocked,dot,wmma,lds}
choose plot mode
-nonKDim {32}         mfma instruction dim, only 32 is supported for now
-sizePerThread SIZEPERTHREAD SIZEPERTHREAD
-threadsPerWarp THREADSPERWARP …
```

Add a cute tool to plot blocked, dotOperand, and mfma layout

---

lib/Conversion/TritonGPUToLLVM/Utility.cpp
test/Conversion/tritongpu_to_llvm.mlir

Inline assembly does not take into account instructions around, and in general can not avoid data hazards.
Replacing inline asm with intrinsics solves this problem. This particular code behaved incorrectly in one of mfma dot tests:
Code generated with help of inline assembly:
```
v_mfma_f32_4x4x4f16 v[4:7], v[4:5], v[6:7], 0
ds_swizzle_b32 v3, v4, offset:swizzle(SWAP:4)
```
Correct code generated with intrinsics:
```
v_mfma_f32_4x4x4f16 v[4:7], v[4:5], v[6:7], 0
s_nop 4
ds_swizzle_b32 v3, v4, offset:swizzle(SWAP:4)
```

Replace inline assembly in commonShflSync with intrinsics

---

lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MFMA.cpp
test/Conversion/AMDGPU/mfma_variants.mlir

MFMA4x4 PR accidentailly removed support of `int8xint8 -> int32` and `fp8xfp8 -> fp32` dot on CDNA. This PR reenables it back.

[MFMA] Reenable removed CDNA3 int and fp8 support

---

python/perf-kernels/hbm-bw-test.py

Change units to GiB/s which is more widely used. Also add option to do both bounds check on and off kernels as we do not always require bounds check on every kernel / loop.

Minor edits to HBM bandwidth measurement kernel

---

include/triton/Dialect/TritonGPU/IR/Dialect.h
include/triton/Dialect/TritonGPU/IR/Traits.h
include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/IR/Traits.cpp
python/test/unit/language/test_core_amd.py

This instruction represents view of the slice of the tensor in registers. Syntax of the operation is the same as for extract_slice op. However, unlike 'extract_slice' which slices in shared memory, 'view_slice' specifically slices within registers.
Slice of the tensor is required to have the same layout as the original tensor. In a way, semantics of the 'view_slice' operation is a combination of the 'extract_slice' and 'view' operations semantics.
This PR adds support for slicing tensors in blocked layout.
TODO: Support slicing in dot layout.

Add view_slice ttgir instruction

---

python/tutorials/06-fused-attention.py

The upstream kernel had some optimizations, specifically for splitting the causal mask across two calls so only one needs to incur the warp divergence penalty. Performance details [here](https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/5357#issuecomment-1879219631).

Merge changes from upstream FA bwd kernel

---

scripts/amd/occ.sh

This PR adds a script that can print out occupancy related information of a kernel.
Example usage: 
```bash
./script/amd/occ.sh ./perf-kernels/06-fused-attention-fwd-transV.py
```
Output
```bash
LDS:  32768, num_warps:  4
VGPRS: 256 (spill: 3)
occ: 2 waves/SIMD (occ_LDS: 2, occ_vgpr: 2)
perf: 127.4 tflops
```
How it works
- LDS usage and num_warps are extracted from the IR
- VGPR usage and spills are extracted from the ISA
- For now, it is assumed
- There are 4 SIMDs per CU
- Total LDS size per CU is 65536 bytes
- Total number of VGPRs per SIMD is 512

[tool] Added a script to print occupancy info

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateAMDMatmul.cpp
python/test/unit/language/test_core_amd.py
test/Conversion/tritongpu_to_llvm.mlir

This PR
- Implements https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/5237
- Supports mfma16 and mfma4 in the fast path
- sets `maxPhase=4` for mfma4. This is because the nonKDim of mfma4 is less than 16.
- Choose warpsPerTile according to mfmaLayout's nonKDim
- cleans up format
Before we enable vector access to LDS for non k-major tensors, here are our conventions about LDS accesses:
- LDS write
- For k-major tensors, swizzling is enabled, i.e. a vector of elements are swizzled in LDS. ds_write are vectorized
- For non k-major tensors, a.k.a. mn-major tensors, swizzling is disabled, i.e. elements are written to LDS in their original order. The LLVM backend usually vectorizes ds_write for us, though we write one element at a time.
- LDS read
- For k-major tensors, …

[Backend] Refactor sharedToDotOperandMFMA lowering

---

.github/workflows/amd-offline-tests.yml
backend/driver.py

Due to recent upstream changes: https://github.com/openai/triton/pull/2929
Also after we update the amd backend in the upstream repo, we need to stage the change.

[AMD backend] Treat metadata as a tuple instead of a dict

---

include/triton/Dialect/TritonGPU/Transforms/Passes.h
include/triton/Dialect/TritonGPU/Transforms/Passes.td
lib/Dialect/TritonGPU/Transforms/CMakeLists.txt
lib/Dialect/TritonGPU/Transforms/DotSlicing.cpp
python/src/triton.cc
python/triton/compiler/compiler.py
python/triton/runtime/jit.py
python/triton/third_party/hip/hip_backend.py
python/tutorials/06-fused-attention.py
test/TritonGPU/dot-slicing.mlir

This PR implements the dot slicing pass. It slices along the k dimension
in a dot operation (for dot A, B with shape(A) = (m,k), shape(B) = (k,n)).
The slice size along the k dimension is set by 'sliceKTile'.
The algorithm includes three main steps:
1) Modify load instruction layouts for dot operands.
- This ensures tensor slices have the same layout as the original tensor,
allowing slicing without data exchange between threads.
2) Slice the dot operands.
- Here, the original dot operands are sliced, starting from the load
instruction. This helps in hiding latency in global memory transactions.
Currently, the algorithm assumes the original tensor undergoes only
elementwise operations before being used as a dot operand. In other
words, the algorithm expects only elementwise operations and …

Dot slicing pass

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td

This PR is actually doing more than I expected
- 2% ~ 4% improvement for large gemm on MI300X when using mfma**32**
- 130% improvement for large gemm on MI300X when using mfma**16**
Therefore, using mfma16 now has better performance on MI300X

Fix vecSize for fp8 and int8 on MI300

---

lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
test/Conversion/AMDGPU/load_store.mlir
test/Conversion/tritongpu_to_llvm.mlir

I'm not quite sure why the existing code for load vectorization is using segmented short-vectorized loads instead of using a full 128-bit load. Using multiple copies of shorter load seems to create a dependency on the LLVM backend (esp. the load and store vectorizer) for full vectorization. This might be fragile as I saw in some cases the vector combine pass and the jump threading pass screwed it up and resulted in non-ideal vectorization.

Use full-vectorized load instructions for load vectorization

---

python/perf-kernels/03-matrix-multiplication-all-types.py

Reduce the tolerance used to checking correctness. Previous big difference is mainly caused by the format `fp8e4m3b8`, which introduced big rounding error in converting subnormal values. The change is to avoid subnormal values when generating inputs. 
With that workaround, we can use much less tolerance in checking the correctness.

refine tolerance in checking GEMM correctness

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
include/triton/Dialect/TritonGPU/Transforms/Utility.h
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MFMA.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateAMDMatmul.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
python/test/unit/language/test_core_amd.py
python/triton/language/semantic.py
test/TritonGPU/accelerate-matmul-cdna1.mlir
test/TritonGPU/accelerate-matmul-cdna2.mlir
test/TritonGPU/accelerate-matmul-cdna3.mlir

This PR enables two new MxN tile sizes: 64 x 4 and 4 x 64. Both of them uses mfma 4x4 instructions.

[MFMA] Support 64x4 and 4x64 tile size

---

python/perf-kernels/03-matrix-multiplication-all-types.py
python/perf-kernels/06-fused-attention-fwd-transV.py
python/tutorials/03-matrix-multiplication.py

This PR adds the FA qkfp8 kernel, in which only the first gemm is done in fp8.
To make things simpler, it is assumed that the torch has native support for AMD fp8 data types.
And also remove ( ) in gemm thanks to fix in https://github.com/ROCmSoftwarePlatform/triton/pull/445

[FA-qk-fp8] Add fp8 FA to 06-fused-attention-fwd-transV.py

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td

Transposed operand will be accessed in an opposite order from the original operand. Enabling swizzling seems to help performance. I'm seeing 10% performance improvement for our internal model.

Enable swizzling SMEM for transposed dot operand

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
python/perf-kernels/03-matrix-multiplication-all-types.py
scripts/amd/gemm/tune_gemm.py

Fixes the issue in https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/6819

Fix a bug in fastPath condition

---

python/tutorials/06-fused-attention.py

- Check correctness for fp8 inputs only when torch supports it
- Only run benchmark in fp16

Fix FA tutorial

---

scripts/amd/gemm/tune_gemm.py

Added init strategies:
1) trig_float: element at col i in row j gets value sin(i)
2) hpl: uniform random in [-0.5, 0.5)
3) randn: default, uniform random in [0, 1)
4) zeros: all 0.0s

[GEMM] [Tuning] Option to try different initialization strategies

---

lib/Dialect/TritonGPU/Transforms/AccelerateAMDMatmul.cpp
python/triton/language/semantic.py

This PR moves casts of operands from python code and ttg to llvm phase to AccelerateAMDMatmul pass

[MFMA] Move operand casts to AccelerateMatMul pass

---

lib/Dialect/TritonGPU/Transforms/AccelerateAMDMatmul.cpp
python/triton/language/semantic.py

Reverts ROCm/triton#477 since it breaks when inputs are f8.

Revert "[MFMA] Move operand casts to AccelerateMatMul pass"

---

scripts/amd/parse_ir_dump.py

Added a simple python script that can take the TTIR+TTGIR, LLVM IR and Assembly dump (at least one of these) and parse them into individual files per each pass. This could help someone understanding what each compilation pass does.
The script takes very basic assumption of the dump and look for anchors for regex so it could be easily broken if any anchors changed.

added ir dump parsing script

---

python/perf-kernels/06-fused-attention-fwd-transV.py
python/perf-kernels/06-fused-attention-transV.py

`06-fused-attention-fwd-transV.py`:
1. Added bfloat16. `test_op_fwd` has 2 testcases failing, each of which has two elements in the final output right outside the error threshold.
2. Can skip fp8 is it is not available in the docker image.
`06-fused-attention-transV.py`:
1. Enabled bfloat16 for both forward and backward, though backward pass fails the testcases. Since we don't really run backward now, I left it aside.

added bf16 support for perf-kernels

---

scripts/amd/check_test_core.sh

This script runs each function in `test_core.py` separately and
- It can catch the core dump error and continue to run the next test function
- It writes pytest output for each function in a separate file 
- It writes the summary, which is more simplified than pytest summary, into another file
1. **copy this script in upstream triton dir. Any location works since it can find its way to the `python` dir**.
2. Run it: `./check_test_core.sh`
The summary and pytest output for each test function are written to `/python/test_output/`.
```bash
Running test_core.py on run_test_core@35edd6a65
test_empty_kernel:                           12 passed
test_bin_op:                                 720 passed, 38 warnings
test_addptr:                                 24 passed
test_floordiv: …
```

Add a script to run tests in `pytest test_core.py` separately

---

lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp

Unifying some code in RemoveLayoutConversions.cpp between NV and ROCm. The current ROCm path misses some update from the main repo.

Unify hasConvertToMMATransisitiveUse

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp

- remove unused functions and variables
- replace "group" with block to unify language
- add check for swizzling pattern compatibility with normal path
- unify normal and fast path index computation

[AMD] Refactor SharedToDotOperandMFMA

---

python/triton/common/build.py

Fix a problem reported by [Pytorch CentOS docker creation failed due to Triton compilation, ImportError: libamdhip64.so.6](https://ontrack-internal.amd.com/browse/SWDEV-443861)
Analysis of this problem:
1. Some Triton libraries do not have `/opt/rocm/lib` in their `RUNPATH`. This leaves `ld` with only two options to find the `libamdhip64.so.6` file: `LD_LIBRARY_PATH` and `/etc/ld.so.conf`.
2. `LD_LIBRARY_PATH` may not contain `/opt/rocm/lib`
3. `/etc/ld.so.conf.d/*` files are being deprecated by ROCM and not reliable. `RUNPATH` is the new preferred way by ROCM to locate ROCM libraries, to support parallel installations.

HIP: Add RUNPATH to compiled so files.

---

scripts/amd/lit_tests/README.md
scripts/amd/lit_tests/generate_accelerate_matmul_tests.py
scripts/amd/lit_tests/generate_mfma_variants.py
test/Conversion/AMDGPU/mfma_variants.mlir
test/TritonGPU/accelerate-matmul-cdna1.mlir
test/TritonGPU/accelerate-matmul-cdna2.mlir
test/TritonGPU/accelerate-matmul-cdna3.mlir

This PR adds scripts for lit test generation.

[MFMA][Test] Add scripts generating mfma related lit tests

---

python/perf-kernels/flash-attention.py

* this pr prevents an issue with a large bias tensor leading to segfaults on some configs due to pointer arithmetic overflow. Triton is unable to address tensors with elements larger than int32 max
* we add an assert to the op to catch cases in the future.
* the solution is to split the forward test in to one with bias and one with out with appropritate config

Bias segfault workaround

---

python/triton/third_party/hip/hip_backend.py

By replace oclc_daz_opt_off.bc with *_on.bc, _exp2_f32() function will not perform the operand subnormal check and adjust the computation of exp.
@jtang10  Can you add you python code to explain the difference here?

Enable fast-exp

---

scripts/amd/fix_so.sh
scripts/amd/setup_rocm_libs.sh

* Make first argument to provide wheel location mandatory
* Make ROCM_VERSION argument mandatory for setup_rocm_libs.sh
(cherry picked from commit 4d510c3a44d23aacfbce21ed1b2853e8e09e9f90)

[release/pytorch_2.2] Update required arguments for build scripts

---

python/perf-kernels/03-matrix-multiplication-all-types.py
python/perf-kernels/flash-attention.py
python/triton/runtime/autotuner.py
python/triton/testing.py

This change is from the upstream PR https://github.com/openai/triton/pull/3306. Integrate the changes to this fork for more correct tuning results.

Integrate cudagraph to autotuning 

---

lib/Dialect/TritonGPU/Transforms/DotSlicing.cpp
test/TritonGPU/dot-slicing.mlir

A `loadop` can have multiple operands such as the mask, which should be sliced as well.

[DotSlicing] Support slicing multiple operands of a load

---

lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
python/test/unit/language/test_core_amd.py

This PR is to fix the UT `test_atomic_cas` by enabling the atomic MemoryOrdering.
Also enhance the the unit test `test_atomic_cas` by increasing the number of work groups in the kernel.

enable atomic MemoryOrderings

---

scripts/amd/gemm/tune_gemm.py

Update tune_gemm.py to use absolute paths, ensuring its proper execution from various directories. This change is a prerequisite for updating the benchmark script in msft_amd_ai_operators, which will invoke tune_gemm.py from there.

Use absolute paths in tune_gemm.py

---

python/perf-kernels/flash-attention.py

skip `test_op_bwd` which is broken with the upstream version of the compiler

Skip test_op_bwd

---

python/perf-kernels/flash-attention.py

Change all block pointers to tensor pointers
Block pointers are for nvidia TMAs. They are useful for regular loads as well but not well supported.
Also cleaned up some code I came across along the way and updated comment at the top.

Change all block pointers to tensor pointers

---

scripts/amd/occ.sh

Recently upstream introduced local_load and local_alloc ops, which fall into the delete list of occ.sh's post processing step. This PR fixes this issue so that we won't delete those two ops in the IR.

Fix post-processing to exclude local_load and local_alloc

---

python/perf-kernels/flash-attention.py

Add support for layouts commonly used by users.
Add option for varlen / thd layout to specify equal context lengths for all batches. Also often used by users.

Add support for layouts

---

scripts/amd/gemm/tune_gemm.py

-Update tune_gemm.py to save benchmarking results in a file. 
-Append the tuning or benchmarking results to an output file. This is because the run_triton scripts in msft_amd_ai_operators tune the gemm configurations one by one, and I'd like to save all tuning results in one single file so that I can use it to benchmark tuned configs all at once.
This change is a prerequisite for [this PR](https://github.com/ROCm/msft_amd_ai_operators/pull/367).

Update tune_gemm.py to save benchmarking results in a file

---

python/perf-kernels/streamk/tune_streamk.py

1. fix the issue of using test_correctness 
2. add another rule in prune_configs to rule out the combination of mfma16 && kpack=2 && block_k=16

fix correctness test issue of tune_streamk

---

scripts/amd/gemm/tune_gemm.py

LDS usage is now multiplied by num_stage. It still checks for num_stages=0 in case stream pipeline is still used

prune LDS usage for the new pipeliner

---

.github/workflows/amd_perf_kernel_Integration_tests.yml
.github/workflows/amd_perf_kernel_postmerge_tests.yml

Some new tests are taking too long and timing out the runner. This was triggered by increasing the autotuning keys for flash attention.

Increase CI timeout

---

scripts/amd/gemm/README.md
scripts/amd/gemm/matmul_kernel.py
scripts/amd/gemm/tune_gemm.py
scripts/amd/gemm/utils/file_generator.py
scripts/amd/gemm/utils/name_utils.py
scripts/amd/gemm/utils/utils.py
scripts/amd/occ.sh

Please check the README for changes introduced in v3.3.
This PR enables
- Put all the kernels to be compiled in a single file ==> this greatly reduces compilation time. In the example of M=N=K=512 which has about 3800 configs, the compilation time reduces from 50 minutes to 1.5 minutes.
- Extract GPU kernels of all configs into a separate file and let compile and profile driver files import it. In this way, compile and profile stages can shared the cache.
- Allow reuse of compiled kernels across different gemm sizes. This is achieved by 
- keeping track of the tuning space across the tuning loop, i.e. at every iteration, we only add new configs from the current gemm size into the tuning space.
- remove M_N_K from the configStr in kernel name
- Refactor the script. Now some utility …

[tuning] gemm tuning script v3.3

---

CMakeLists.txt

Required to build triton successfully using gcc8. Without this fix, the llvm static libraries built on gcc8 would have references to std::filesystem symbols which would show up as linker errors about undefined symbols when linking triton executables.
eg.
```
../lib/Target/LLVMIR/libTritonLLVMIR.a(LLVMIRTranslation.cpp.o): In function `mlir::triton::getExternLibs(mlir::ModuleOp)':
/usr/include/c++/8/bits/fs_ops.h:121: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/include/c++/8/bits/fs_ops.h:121: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
../lib/Target/LLVMIR/libTritonLLVMIR.a(LLVMIRTranslation.cpp.o): In function `mlir::triton::getExternLibs(mlir::ModuleOp)':
/usr/include/c++/8/bits/fs_path.h:185: …
```

[release/internal/2.0] std::filesystem fix for gcc8 builds

---

python/perf-kernels/README.md
python/perf-kernels/multreduce_matmul_kernel.py

Add kernel that implements GEMM with explicit multiply-reduce instructions for small block sizes. Such
small block sizes aren't natively supported by `tl.dot` operator.
Despite being numerically correct, this kernel performed worse than a corresponding GEMM kernel that
used `tl.dot` with minimum block size equal to $16$:
**MI300 Results for FP16:**
| trans   |   M |     N |     K |         Dot GiBps |   Multiply-Reduce GiBps |   Speedup |
|:--------|----:|------:|------:|------------------:|------------------------:|----------:|
| TN      |   1 |  8192 | 28672 |           3491.33 |                 2869.87 |      0.82 |
| TN      |   1 |  6144 |  6144 |           3858.22 |                 2673.33 |      0.69 |
| TN      |   1 |  4096 |  4096 |           2352.54 |                 1680.93 | …

Add explicit multiply-reduce GEMM kernel

---

python/perf-kernels/tune_gemm/README.md
python/perf-kernels/tune_gemm/icache_flush.py
python/perf-kernels/tune_gemm/matmul.py
python/perf-kernels/tune_gemm/matmul_kernel.py
python/perf-kernels/tune_gemm/one_config.py
python/perf-kernels/tune_gemm/rocprof_gemm.py
python/perf-kernels/tune_gemm/tune_gemm.py
python/perf-kernels/tune_gemm/tune_gemm.sh
python/perf-kernels/tune_gemm/utils/file_generator.py
python/perf-kernels/tune_gemm/utils/utils.py

The source commit in `triton-mlir` branch is the following one:
```
commit cf44637139ba441342b909977f51f7cfec2c9963
Author: Lixun Zhang <Lixun.Zhang@amd.com>
Date:   Tue Jul 23 14:22:01 2024 -0500
[tuning] gemm tuning script v3.3 (#606)
```
*tune_gemm* was copied from the source branch directory `scripts/amd/gemm`
to the destination branch directory `python/perf-kernels/tune_gemm`.
The SHA-256 hashes of *tune_gemm* files are the following ones:
```
423aef1deb6c60f6578a1ecfc94d2473f8746b00d0368c553d31641fcfa5e354  README.md
46ab93978fee33f75df23332f12546dae7910478c391f08b7b1ebd415d8266b7  icache_flush.py
f18711544641b810a652e6a6629bfa2b613f6ade87399e88fdf05b81d4af58a4  matmul.py
84a1c80ede36d3154e51188276eda2d2d0f52ed4f496ff69349c390d83b8ec10  matmul_kernel.py …
```

Copy *tune_gemm* from `triton-mlir` branch to `main_perf` branch

---

python/perf-kernels/tune_gemm/README.md
python/perf-kernels/tune_gemm/matmul_kernel.py
python/perf-kernels/tune_gemm/tune_gemm.py
python/perf-kernels/tune_gemm/utils/file_generator.py

This PR reverts https://github.com/ROCm/triton/pull/613 since there is a severe problem with rocprofv2 described in [ticket#228](https://github.com/ROCm/triton-internal/issues/228).
The problem is that rocprofv2 will "miss" a lot of kernels in the tuning space. Therefore, sub-optimal config is picked.
We will switch back to rocprofv2 when the issue is resolved.
This PR also enabled xcd-based pid remapping. I need to run more experiments to understand the effects of xcd-based remapping and group_size_m (as described in [ticket#229](https://github.com/ROCm/triton-internal/issues/229)).
To disable xcd-based remapping, change this [line](https://github.com/ROCm/triton/blob/cba3d193ab5188073fb787dc0de89fc7fb718cd0/python/perf-kernels/tune_gemm/matmul_kernel.py#L15) from 
```python
if NUM_XCDS …
```

[tune gemm v3.4] Add xcd-based pid remapping and change back to rocprofv1

---

python/perf-kernels/streamk/streamk_kernel.py

streamk gemm kernel is using spinning lock to implement multiple buffer method to replace atomic_add, 
The [PR 4431](https://github.com/triton-lang/triton/pull/4431) cause data racing when using atomics_xchg and atomics_cas together to implement [spinning lock.] atomic cas uses shared memory but atomics_xchg doesn't.(https://github.com/ROCm/triton/blob/624335ff569562d5db26bea337e3c6de2bd6b0dc/python/perf-kernels/streamk/streamk_kernel.py#L173C12-L205C1)
In Triton, atomic operations are performed at the block level, where each block can consist of multiple waves. The purpose of adding synchronization is to ensure that waves wait until the current wave has completed its execution.

streamk atomics fix

---

python/perf-kernels/flash-attention.py

code to use custom navi configs. The People working on navi perf want their own configs and keys for running the kernels. They just need to provide that

add RDNA Config

---

.github/workflows/amd_perf_kernel_Integration_tests.yml
python/perf-kernels/multreduce_matmul_kernel.py

This PR adds missing test and benchmark features to the explicit dot GEMM Triton kernel developed in the scope of https://github.com/ROCm/triton-internal/issues/169. It also adds GEMM implemented with `tl.dot` to the mix so we can easily compare it to PyTorch GEMM and Triton GEMM implemented with explicit dot, both in terms of correctness and performance.
```bash
python python/perf-kernels/multreduce_matmul_kernel.py -h
```
```
usage: multreduce_matmul_kernel.py [-h] [-M M] [-N N] [-K K] [--use-bias] [--use-dot] {run,bench}
C = A * B + BIAS matrix multiplication kernel for small matrices (M ≤ 8)
positional arguments:
{run,bench}  mode of operation:
run: run Triton kernel for a given (M, N, K) shape
bench: benchmark performance for target shapes
options:
-h, --help   show this help message …
```

Add test and benchmark for explicit dot GEMM
