- python/test/unit/language/test_core.py
added a check before trying to look ptx for. It fixed the first two but the last one has another failure.
* test_vectorization 
* test_load_cache_modifier 
*  test_permute
> fix test_vectorization and test_load_cache_modifier

- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
- python/tests/test_core_amd.py
Will need to revisit these changes once we implement vectorized loads and stores.
> Fix StoreOpConversion bug and add test_where to test_core_amd.py.

- triton_rocm_20-52.Dockerfile
- Removing setting of MI_GPU_ARCH
> Updating the Dockerfile

- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
This PR fixes the incorrect bitcast call in the AMDGPU implementation of StoreOpConversion.
It was causing issues because in certain use cases, the previous insert_element call was packing 2 fp16s into a single 2xfp16 vector.
The bitcast incorrectly assumed that the packed 2xfp16 vector was a single fp16 value and therefore caused an LLVM error.
The current scheme eliminates the need to use insert_element altogether and still preserves the vector store capability.
> Fix store op conversion to eliminate incorrect bitcast call.

- python/triton/compiler.py
The change is based on Rohit' commit 9bf807f,
where launch triton with HIP on AMD GPU was implemented.
Some parts of online tests started to pass.
Further fixes in these tests will be separate changes.
> [Triton-MLIR][ROCM] Launch triton on AMD GPU.

- python/src/triton.cc
- python/tests/test_ext_elemwise.py
- python/triton/language/core.py
- python/triton/language/libdevice.py
- python/triton/language/semantic.py
This PR enables several functions in tl.libdevice for AMDGCN.
This delivers a 100% pass rate for test_elemwise.py and a 100% pass rate for test_ext_elemwise.py.
> AMDGCN fixes for libdevice.py.

- python/test/unit/language/test_dequantize.py
- python/test/unit/language/test_random.py
- python/test/unit/operators/test_blocksparse.py
> Skip Segfaults

- python/triton/compiler.py
- python/triton/language/libdevice.py
/cc @whchung @micmelesse @weihanmines
> Gfx90a fix for amdgcn bitcode discovery

- python/src/triton.cc
Cherry-picked into `triton-mlir-phase-2` from https://github.com/ROCmSoftwarePlatform/triton/pull/57
> [ROCm] Added support for ShiftOps for AMDGPU

- lib/Conversion/TritonGPUToLLVM/GcnAsmFormat.cpp
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
- python/tests/test_core_amd.py
storeShared and shflSync implemented.
> [ROCm] Lowering ReduceOp with inline asm. Logical warpSize 32 is assumed.

- lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
- python/triton/compiler.py
Some minor fixes which enable a 99% pass rate for test_core_amd.py.
> Triton mlir ifu fixes

- python/tests/test_core_amd.py
Added some tests to test_core_amd.py from original test_core.py to check regresssion in commits.
Passed tests count increased from 2955 to 3259.
> [Triton-MLIR][NFC] Add tests that are already passing.

- CMakeLists.txt
- python/triton/compiler.py
This will be useful for upstream integration as well as comparisons betweeen platforms.
> Fixes to enable triton-mlir branch to build on Nvidia.

- python/test/unit/language/test_core.py
- python/triton/language/core.py
Fixing problem 2 in https://github.com/openai/triton/issues/1017
Co-authored-by: Philippe Tillet <phil@openai.com>
[Edit: this cherry pick fixes the `AssertionError: cannot convert None to tensor`]
> [Frontend] Convert constexpr to value for store and load ops (#1030)

- lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
- python/test/unit/language/test_core_amd.py
- python/tutorials/05-layer-norm.py
This resolves issues with the masked load and store implementations to avoid executing the load or store respectively when the maskVal is false.
This enables 100% functional correctness for the softmax and layernorm forward pass tutorials.
This also updates test_core_amd.py with some unit tests that were enabled by this (and some that should have been enabled in the past).
Finally, some tweaks were made to the layernorm tutorial to reflect the current state of atomics support for AMDGPU and to improve performance on AMDGPU.
> Fix for masked load store

- lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
Avoid executing loads/stores when the maskVal is false.
> Fix for masked load/store for AMDGPU.

- lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
Masked load and store have been implemented vis scf dialect. One more step is added to conversion pipeline for ROCm.
- The implementation has numerical issue when running fused-softmax. The issue is under investigation.
> Support Masked Load/Store via SCF

- python/setup.py
This critically fixes missing lit binary by ignoring it.
> this brings setup.py up to date with upstream

- test/Conversion/AMDGPU/load_store.mlir
This PR fixes Conversion/AMDGPU/load_store.mlir lit based unit test.
related issue #82
> [Test][Lit] Fix load_store test

- test/Conversion/tritongpu_to_llvm.mlir
This PR fixes lit based unitest Conversion/tritongpu_to_llvm.mlir for GCN target.x
related Issue #82
> [Test][Lit] Tritongpu to llvm

- python/triton/compiler.py
- python/triton/tools/aot.py
Add missing triple and features arguments to aot.py.
> [FRONTEND] Fix llir_to_amdgcn_and_hsaco arguments in aot.py

- python/triton/tools/aot.py
This pr separates options in frontend for PTX and GCN targets in aot.py.
related issue: #82
> [FRONTEND] remove compute copability option for AMD targets

- test/Target/tritongpu_to_amdgcn.mlir
- test/Target/tritongpu_to_hsaco.mlir
This PR fixes tritongpu_to_hsaco.mlir test,
plus fixes minor issue with tritongpu_to_amdgcn test
> [Test][LIT] Fix tritongpu_to_hsaco.mlir test

- lib/Target/HSACO/HSACOTranslation.cpp
This PR removes the use of the unsafe tmpnam call for generating the HSACO file name.
This was causing an error in the integration test.
> Remove the unsafe tmpnam call to generate the HSACO file name.

- python/triton/compiler.py
The changes in this PR were a slight functionality gap I noticed while helping to debug a Pytorch 2.0 related issue.
> Upgrade HIP launcher code to be at parity with CUDA.

- python/triton/compiler.py
See issue https://github.com/openai/triton/issues/1228
> Add static to _launch function call

- python/tutorials/02-fused-softmax.py
- python/tutorials/05-layer-norm.py
- test/Target/mlir_to_amdgcn_float16_vectorized_load_store.mlir
- test/Target/mlir_to_amdgcn_int16_vectorized_load_store.mlir
Reduce the num_warps for layernorm and softmax.
Fix some lit unit tests.
> Some warp64 related fixes.

- lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
This PR enables conversion of natural exponential function to approximate version using equation exp(x) = exp2(x*log2(e))
This implementation tries to match PTX variant.
> [Triton-MLIR] Enable approximate exp conversion for AMD GPUs

- bin/triton-opt.cpp
- include/triton/Dialect/Rock/Passes.td
- test/dot-rocMLIR/Rock/lowering_blockwise_gemm_v2.mlir
- test/dot-rocMLIR/Rock/lowering_buffer_ops.mlir
- test/dot-rocMLIR/Rock/lowering_in_bounds_ops.mlir
- test/dot-rocMLIR/Rock/lowering_transforming_for.mlir
- test/dot-rocMLIR/Rock/lowering_xdlops_gemm_v2.mlir
- test/dot-rocMLIR/Rock/sanity.mlir
- test/dot-rocMLIR/Rock/vector_slices.mlir
This PR enables the transforms inside the Rock dialect. It also adds 7 unit tests from the rocMLIR project to check the lowering passes.
> [dotOp] [rocMLIR] Add Rock transforms and unit tests

- python/triton/compiler.py
Adding lost part of tl.device_print implementation in PR 182.
> [ROCM] Fix for tl.device_print.

- python/batch_prof.sh
- python/tritonProfiler.sh
This PR refines the tuning scripts to be prepared to check in triton perf numbers
> [dotOp] [rocMLIR] [Tuning] Refine the tuning scripts

- python/triton/compiler.py
- python/tritonProfiler.sh
> [dotOp] [rocMLIR] [tuning] Add kpack and mPerWave to fn_hash and fix the cache issue

- .gitignore
- bin/triton-translate.cpp
- include/triton/Conversion/TritonGPUToLLVM/Passes.td
- include/triton/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.h
- lib/Target/LLVMIR/LLVMIRTranslation.cpp
- python/triton/compiler/compiler.py
- python/triton/tools/aot.py
- scripts/amd/build.sh
- scripts/amd/docker_run.sh
- scripts/amd/pytorch.sh
- scripts/amd/run.sh
- scripts/amd/test.sh
- test/Target/tritongpu_to_llvmir.mlir
> fix pyt 2.0 issues

- python/batch_prof.sh
- python/tritonProfiler.sh
For now, need to choose the driver manually in batch_prof.sh, which means large gemms (M>16) and small gemms (M <=16) need to be tuned separately.
> [rocMLIR] [tuning] Automatically remove groupM for small M (<=16)

- lib/Analysis/Utility.cpp
- lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
- python/test/unit/language/test_core_amd.py
- python/tutorials/06-fused-attention.py
Patch contains following changes:
1) make_range operator now works in MFMA layout. 
2) Reduce operator now  works in MFMA layout with matchAndRewriteBasic
algorithm codegen.
> [MFMA] Enabled fused attention forward pass.

- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
- python/triton/compiler/compiler.py
This PR enables support of sliced tensors of dot operands.
One of consequences is we can reenable prefetch and sw pipeline optimizations.
> [Dot] Support slicing in dot operands

- CMakeLists.txt
- include/triton/Conversion/TritonToTritonGPU/Passes.td
- include/triton/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.h
- include/triton/Dialect/TritonGPU/IR/Dialect.h
- include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
- include/triton/Dialect/TritonGPU/IR/TritonGPUDialect.td
- include/triton/Dialect/TritonGPU/Transforms/TritonGPUConversion.h
- lib/Analysis/Utility.cpp
- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
- lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
- lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/Transforms/Coalesce.cpp
- lib/Dialect/TritonGPU/Transforms/TritonGPUConversion.cpp
- python/src/triton.cc
- python/test/unit/language/test_core_amd.py
- python/triton/compiler/compiler.py
- python/triton/compiler/make_launcher.py
- python/triton/runtime/jit.py
- python/triton/tools/aot.py
- test/Conversion/triton_to_tritongpu.mlir
Fixes https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/4521
> Dynamic Warp Size to enable Navi 2x/3x support

- include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
- lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MFMA.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
- python/test/unit/language/test_core_amd.py
- test/Conversion/tritongpu_to_llvm.mlir
This PR adds more attributes to MFMA layout to align with dot-rocMLIR branch.
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/4660
> [MFMA] Parameterize MFMA layout with non k dimension size

- include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
This PR supports swizzling in MFMA dot operands.
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/4658
> [MFMA][Dot] Swizzle mfma dot operands 

- lib/Dialect/TritonGPU/Transforms/ReorderInstructions.cpp
Enable moving shared->dot conversion after dependent load. For the Q tensor in flash attention, the shared->dot conversion acts as a loop invariant. Moving this conversion post dependent load will hoist the conversion outside the loop. Consequently, during computation, we will be able to maintain the Q tensor in the registers.
> [FA] Keep Q tensor in registers.

- python/test/unit/language/test_core_amd.py
- python/triton/compiler/compiler.py
This PR sets default value of pipeline stages to 1 for amd. Add explicit num stages in test_gemm test
> Disable pipelining

- python/tutorials/06-fused-attention.py
Enabled the backward pass in the fused attention tutorial. The tolerance when comparing to the naive implementation had to be changed. The block size is forced to be 64x64 due to the 64 KiB LDS. Default is block 128 for A100's larger SMEM. This creates differences in order of computation and reuslts in a larger gap between the naive and FA implementations.
> Enable backward pass in FA tutorial test

- python/tutorials/03-matrix-multiplication.py
This pr adds amd specific tuning configs for matmul tutorial with num_stages == 1.
> [tutorial] Amd specific tuning configs

- python/tutorials/03-matrix-multiplication.py
With the simple changes in the scripts, we can boost the performance by 3x for the matmul tutorial example, so we commit the changes here. 
Specific reason for the performance boost needs further investigation and are tracked internally.
> Changes of the tutorial matmul scripts to get good performance

- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
This PR replaces expensive operations with simpler ones: mul,div are replaced with select and compare.
This is minor change, it decreses number of required registers when dot operation loading is a bottleneck by one.
> [MFMA] More optimal offset computation

- python/test/unit/language/test_core_amd.py
Use upstream list of test for dot op on machines with no MFMA support. This is needed to reduce time required for PR testing.
> [CI] [Dot] Reduced test suite

- python/triton/runtime/autotuner.py
With this PR, we can print out the best config for each key by adding `verbose=True` in `@triton.autotune` like
```python
@triton.autotune(
configs=[
triton.Config({'BLOCK_SIZE_M': 128, 'BLOCK_SIZE_N': 256, 'BLOCK_SIZE_K': 64, 'GROUP_SIZE_M': 8}, num_stages=3, num_warps=8),
triton.Config({'BLOCK_SIZE_M': 64, 'BLOCK_SIZE_N': 256, 'BLOCK_SIZE_K': 32, 'GROUP_SIZE_M': 8}, num_stages=4, num_warps=4),
triton.Config({'BLOCK_SIZE_M': 128, 'BLOCK_SIZE_N': 128, 'BLOCK_SIZE_K': 32, 'GROUP_SIZE_M': 8}, num_stages=4, num_warps=4),
triton.Config({'BLOCK_SIZE_M': 128, 'BLOCK_SIZE_N': 64, 'BLOCK_SIZE_K': 32, 'GROUP_SIZE_M': 8}, num_stages=4, num_warps=4),
triton.Config({'BLOCK_SIZE_M': 64, 'BLOCK_SIZE_N': 128, 'BLOCK_SIZE_K': 32, 'GROUP_SIZE_M': 8}, num_stages=4, num_warps=4), …
```
> [Autotuner] Print out best config for each key

- lib/Target/HSACO/HSACOTranslation.cpp
generate_hsaco should probably be rename at somepoint since we're doing more than just hsaco files.
> Add bitcode writer to AMDGCN hsaco output

- lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
Disable reorder of dot arguemnts for amd gpu.
> [Dot] Fix FMA fp16xfp16 dot

- python/tutorials/06-fused-attention.py
This PR replaces qk matrix initialization with
upstream version
> [FA] Upstream FA qk initialization

- python/tutorials/06-fused-attention.py
This commit reverts num_warps back to 4 for FA forward pass with d=128.
> [FA] Fix bug from IFU merge

- lib/Analysis/Utility.cpp
- lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MFMA.cpp
- lib/Conversion/TritonGPUToLLVM/TypeConverter.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
- python/test/unit/language/test_core_amd.py
- test/Conversion/tritongpu_to_llvm.mlir
This PR changes kWidth semantics "from elements per instruction" to "elements per thread per instruction" along k axis.
> [MFMA] Change kWidth parameter semantics

- include/triton/Analysis/Allocation.h
- include/triton/Dialect/TritonGPU/IR/TritonGPUDialect.td
- lib/Analysis/Allocation.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- test/Conversion/minimize_alloc.mlir
- Use disjoint alias analysis to minimize shared memory requirements
Fixes: https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/5627
> [Alloc] Enhanced SharedMem Allocation for mutually exclusive but aliased buffers

- README.md
Cherry picked from upstream [#2344](https://github.com/openai/triton/pull/2344) and some tweaks from [#2381](https://github.com/openai/triton/pull/2381)
I tested in my local container and it builds after I installed libzstd
sudo apt install -y libzstd-dev
> [DOC] Add instructions for building with custom LLVM (#2344)

- lib/Dialect/TritonGPU/Transforms/StreamPipeline.cpp
- test/TritonGPU/stream-pipeline.mlir
This fixes the case where not all loads are pipelined but they have shared dependencies.
> [MLIR] Fixed support for mixed data-types in stream-pipeline

- include/triton/Analysis/Utility.h
- lib/Analysis/Utility.cpp
- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
- lib/Conversion/TritonGPUToLLVM/DotOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MFMA.cpp
- lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
- python/triton/language/semantic.py
This PR adds support for mfma with tile size 16.
> [Triton] Mfma16 support

- lib/Conversion/TritonGPUToLLVM/Utility.cpp
Fix for https://github.com/ROCmSoftwarePlatform/triton/issues/367
> Always promote int8 to int32 in commonShflSync

- lib/Analysis/Utility.cpp
- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
- lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MFMA.cpp
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
- lib/Conversion/TritonGPUToLLVM/TypeConverter.cpp
- lib/Dialect/TritonGPU/Transforms/AccelerateAMDMatmul.cpp
- python/test/unit/language/test_core_amd.py
- python/triton/language/semantic.py
This PR adds support of fp8 and bf8 instructions
> [MFMA] FP8 and BF8 support

- lib/Dialect/TritonGPU/Transforms/OptimizeEpilogue.cpp
- python/perf-kernels/06-fused-attention-transV.py
- python/src/triton.cc
- python/triton/runtime/autotuner.py
- python/tutorials/06-fused-attention.py
This commit is cherry-picked from upstream and updated to support MFMA layout as well.
This PR also adds some configs and benchmark parameters.
> Add OptimizeEpilogue pass.

- python/perf-kernels/06-fused-attention-transV.py
- python/triton/runtime/autotuner.py
- python/tutorials/03-matrix-multiplication.py
- python/tutorials/06-fused-attention.py
- scripts/amd/gemm/matmul.py
Cherry picked from https://github.com/openai/triton/pull/2534
> [FRONTEND] Add input dtypes to autotuning key (#2534)

- python/perf-kernels/06-fused-attention-transV.py
- python/perf-kernels/README.md
- python/tutorials/06-fused-attention.py
Last IFU mixed some upstream and ROCm changes, rendering testing and benchmarking impossible.
This PR fixes merge issues.
> [Tutorial] Fix post IFU issues with FA

- scripts/amd/gemm/README.md
- scripts/amd/gemm/one_config.py
The script runs one given config for debug purposes.
>  [GEMM] Add script to run one tuning config

- scripts/amd/gemm/tune_gemm.py
This PR adds:
- verbose tuning mode: printing std output of compilation and tuning calls
- collecting information about failed compilations
- print correctness check output with word
- split dimensions in generated scripts with "-"
- gpu_ids option to set particular gpus
> [GEMM] [Tuning] Make tuning script more verbose

- include/triton/Analysis/Utility.h
- include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
- include/triton/Dialect/TritonGPU/Transforms/Passes.h
- include/triton/Dialect/TritonGPU/Transforms/Passes.td
- lib/Analysis/Utility.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/Transforms/AccelerateAMDMatmul.cpp
- python/src/triton.cc
- python/triton/compiler/compiler.py
- test/TritonGPU/accelerate-amd-matmul.mlir
-Introduce WmmaEncodingAttr for WMMA output (disabled for now)
-Introduce BlockedToWMMA rewrite pattern in TritonAMDGPUAccelerateMatmulPass
Signed-off-by: joviliast <iveselov.nn@gmail.com>
> [WMMA][Dot] Support WMMA layout in TritonAMDGPUAccelerateMatmulPass

- python/perf-kernels/hbm-bw-test.py
This kernel moves 2^32 bytes of data from one region of memory to another. It sweeps the number of WGs that move this data. There are params to change the block size and whether bounds check is performed.
> Add kernel to check HBM BW

- python/triton/runtime/backends/hip.c
- python/triton/third_party/hip/hip_backend.py
Missed some pieces of these two commits:
https://github.com/ROCmSoftwarePlatform/triton/commit/a9b8c8c37d134d2cb196b36141d4ab2c1b1961f2
https://github.com/openai/triton/commit/30186f401ec52d9addac79a60f418792875f7d11
> [ROCM] drop GIL for launch, and set value=false upon pointer error

- include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/Transforms/AccelerateAMDMatmul.cpp
- python/test/unit/language/test_core_amd.py
- test/Conversion/AMDGPU/mfma_variants.mlir
- test/Conversion/minimize_alloc.mlir
- test/Conversion/tritongpu_to_llvm.mlir
This PR removes CTALayout attribute from MFMA layout, because it is NV specific.
> [MFMA] Remove CTA related code from layout

- scripts/amd/gemm/tune_gemm.py
Solves https://github.com/ROCmSoftwarePlatform/triton/issues/447
> [GEMM] [Tuning] Skip BLOCK_SIZE that is too large compare to M/N

- lib/Dialect/TritonGPU/Transforms/AccelerateAMDMatmul.cpp
Disabled BlockedToWMMA layout transformation until WMMA is supported completely
> [HotFix] Fix dot op for RDNA3 architecture

- lib/Analysis/Utility.cpp
Current implementation is enabled for only mfma32, enable this for mfma16.
> enable layout conversion from mfma to dot_op for mfma16.

- python/perf-kernels/flash-attention.py
Added autotuning for the FA kernel in perf-kernels.
Created a pre_hook function to set up params that depend on autotune parameters before each call.
> Add autotuning for FA

- .github/workflows/amd-offline-tests.yml
- Dockerfile
This PR add builds a docker file that pulls upstream and tests it on a AMD node.
You can build and run unit tests in the dockerfile with the following.
```
docker build -t triton .
sudo docker run -it --rm --network=host --user root --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --ipc=host --shm-size 16G --device=/dev/kfd --device=/dev/dri \
-w /tmp/triton --name triton_container -d triton
docker exec triton_container pytest -n 32 --capture=tee-sys -rfs --verbose "python/test/unit/language/test_core.py"
docker stop triton_container
```
> Dockerfile and test

- python/perf-kernels/03-matrix-multiplication-all-types.py
- Check correctness of what is benchmarked
- Add capability to check col_a and col_b
- But only check col_a=False, col_b=True for now
- Only benchmark col_a=False, col_b=True for now
- Remove in='int8', out='int8' due to too large error
Leftover from https://github.com/ROCmSoftwarePlatform/triton/pull/456
> [GEMM][Tutorial] Refine test_correctness

- python/perf-kernels/flash-attention.py
This reverts commit 1fec965c062c4a5ec2fb0c36ff0a53b56d103d0a.
This change used pre_hook to edit a kernel arg. However, pre-hook does not make the changes made within visible to the kernel in all cases.
> Revert "Add autotuning for FA (#459)"

- lib/Conversion/TritonGPUToLLVM/Utility.cpp
- lib/Conversion/TritonGPUToLLVM/Utility.h
Add helper methods for fp16, bfp16 values
Signed-off-by: joviliast <iveselov.nn@gmail.com>
> Add shortcut for creation fp16, bfp16

- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- test/TritonGPU/accelerate-matmul-cdna1.mlir
- test/TritonGPU/accelerate-matmul-cdna2.mlir
- test/TritonGPU/accelerate-matmul-cdna3.mlir
- Fix layout printing format
- Fix comments in SharedToDotOperandMFMA.cpp
> [MFMA] Cleanup mfma pipeline

- lib/Target/LLVMIR/LLVMIRTranslation.cpp
- scripts/amd/gemm/tune_gemm.py
Also fixed some bugs in the tuning script
This helps small gemms (~ 10us kernels) a lot. One gemm's execution time drops from 9.5 us to 7.5 us.
> Add InReg attribute to function args

- scripts/amd/gemm/tune_gemm.py
For pytorch 1, we cannot pass a dtype to the matmul warmup kernel. This PR adds an option `no_warmup` to disable the pre-compilation stage of the tuning process.
> [GEMM] [Tuning] Add an option to disable warmup compilation

- include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
- include/triton/Dialect/TritonGPU/Transforms/Passes.h
- include/triton/Dialect/TritonGPU/Transforms/Passes.td
- include/triton/Dialect/TritonGPU/Transforms/Utility.h
- lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MFMA.cpp
- lib/Dialect/TritonGPU/Transforms/AccelerateAMDMatmul.cpp
- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- python/src/triton.cc
- python/test/unit/language/test_core_amd.py
- python/triton/compiler/compiler.py
- python/triton/runtime/jit.py
- python/triton/third_party/hip/hip_backend.py
- scripts/amd/gemm/tune_gemm.py
- scripts/amd/occ.sh
This PR adds `kpack` in kernel arg to control the ratio between kWidth and k_base.
> Add option for larger LDS vecSize

- lib/Dialect/TritonGPU/Transforms/StreamPipeline.cpp
- test/TritonGPU/stream-pipeline.mlir
The change enables stream pipelining on dot operation with transposition involved, in particular `tt.dot(Q, tt.trans(K))`. The change also fixes a perf issue where incorrect swizzling code was issued based on pre-transpose layout.
> Support tt.trans in stream pipeliner

- python/src/triton.cc
- python/triton/third_party/hip/hip_backend.py
Make warp size parameter and kernel launching dependent on architecture
Signed-off-by: joviliast <iveselov.nn@gmail.com>
> Provide correct warp size to compiler

- python/perf-kernels/flash-attention.py
Changes max sequence lengths and block dmodel to constexprs. These are used at several locations in the asm in decision trees. Making them constexprs results in significant speedups.
Other stuff cannot be made constexpr or has no / little impact.
Speedup min / max / geomean = 1.0 / 1.23 / 1.12. Perf table:
|    | BATCH | H  | N_CTX_Q | N_CTX_K | Triton      |
|----|-------|----|---------|---------|-------------|
| 0  | 16    | 16 | 1024    | 1024    | 238.866322  |
| 1  | 8     | 16 | 2048    | 2048    | 277.376829  |
| 2  | 4     | 16 | 4096    | 4096    | 304.462148  |
| 3  | 2     | 16 | 8192    | 8192    | 314.47344   |
| 4  | 1     | 16 | 16384   | 16384   | 328.959699  |
| 5  | 2     | 48 | 1024    | 1024    | 185.753668  |
| 6  | 2     | 48 | 2048    | 1024    | 241.538811  |
| 7 …
> Change critical args to constexprs

- python/perf-kernels/flash-attention.py
Retains the ability to run the existing benchmark suite.
> Add ability to specify custom configs at the cmd line

- python/triton/runtime/backends/hip.c
This is trying to enable our AMD backend to print out kernel register usage information like below
```
grids = total_programs_streamk + total_blocking_tiles
kk = theKernel[(grids,)]()
if DEBUG:
print(f"{kk.n_regs} registers used, {kk.n_spills} spills")
```
> enable register usage and spill for AMD backend

- lib/Analysis/Utility.cpp
- lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- python/test/unit/language/test_core_amd.py
This PR fixes several issues with asymmetrical MFMA layouts, fixing reduction op on MFMA and enables related tests.
> [ReductionOp][MFMA] fix reduction of mfma64x4 layout 

- scripts/amd/fix_so.sh
- scripts/amd/setup_rocm_libs.sh
Required for https://github.com/ROCm/pytorch/pull/1373
> [release/pytorch_2.1] Update required arguments for build scripts

- .gitignore
- python/perf-kernels/flash-attention.py
* this is the forward pass for adding alibi to our FA Kernel
> [FA] Alibi Forward Pass

- lib/Dialect/Triton/Transforms/RewriteTensorPointer.cpp
https://github.com/openai/triton/pull/3080
> Cherry pick support for tensor pointer usages in scf::IfOp

- scripts/amd/occ.sh
> [tool] Fix occ

- python/perf-kernels/flash-attention.py
Had to add another autotune config. Get similar performance now to head size 128 but have only checked on a few configs.
> Support head size <= 256

- python/perf-kernels/03-matrix-multiplication-stream-k.py
- python/perf-kernels/streamk/03-matrix-multiplication-stream-k-singlekern-autotune.py
- python/perf-kernels/streamk/03-matrix-multiplication-stream-k-singleloop-nomod.py
this is to enable the kpack and mfma_instr_nokdim tuning options for stream-k
> add kpack and  matrix_instr_nonkdim for stream-k implementation

- python/perf-kernels/flash-attention.py
Adding in the new backwards kernel with minimal testing changes and almost no new features.  Feature commits to follow this commit.
> New base backwards kernel

- python/perf-kernels/flash-attention.py
The new input helper was not used correctly.
> Fix varlen mqa test

- python/perf-kernels/hbm-bw-test.py
Add ability to specify size, wgs and block size at cmd line
Add ability to do a read-only test.
> Add read only benchmark and cmd line config capability

- python/perf-kernels/flash-attention.py
Fix KV head index calculation for MQA / GQA.
Also made HQ and HK constexprs to increase performance by a bit.
> Mqa gqa bugfix

- python/perf-kernels/README.md
Updated the perf-kernels README file with information about the recently added kernels and changes.
> Update perf kernels readme

- .github/workflows/amd-offline-tests.yml
- python/perf-kernels/flash-attention.py
This pr uses github actions to run ci for perf kernels and test_core_amd.py
> CI for Perf Kernels and test_core_amd.py

- .gitignore
- python/perf-kernels/flash-attention.py
This pr adds alibi to the backward pass.
> alibi backward

- .github/workflows/amd-offline-tests.yml
this pr seperates the ci on the triton-mlir branch with that of main.
> seperate ci on triton-mlir and main

- scripts/amd/gemm/README.md
- scripts/amd/gemm/one_config.py
Update one_config.py to support new input parameters.
Fixes https://github.com/ROCm/triton-internal/issues/116
> Update one_config.py to support new input parameters

- python/perf-kernels/streamk/03-matrix-multiplication-stream-k.py
- python/perf-kernels/streamk/persistent_streamk_kernel.py
1. multiple buffer implementation to replace atomic_add
2. add mask to support irregular size of matrices
3. move acc allocation outsize of loop 
4. spinning lock bug fixes.
contributions from  @ravil-mobile @neoblizz @zhanglx13 @scxiao in triton compiler bug fix, stream-k algorithm and various bug fixes.
> non atomic implementation of stream-k

- scripts/amd/amdgcn-cfg/README.md
- scripts/amd/amdgcn-cfg/amdgcn-cfg.py
Added CFG generator for amdgcn assembly files
> CFG generator for amdgcn assembly files
